//>>built
define("dgrid/ColumnSet","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/on dojo/aspect dojo/query dojo/has ./util/misc put-selector/put xstyle/has-class ./Grid dojo/_base/sniff xstyle/css!./css/columnset.css".split(" "),function(x,y,q,z,h,r,n,e,A,p,B,F){function C(a,b){function c(){n(".dgrid-column-set",b).forEach(function(a){a.scrollLeft=d[a.getAttribute(k)]})}var d=a._columnSetScrollLefts;8>e("ie")||e("quirks")?setTimeout(c,1):c()}e.add("event-mousewheel",function(a,
b,c){return"undefined"!==typeof c.onmousewheel});e.add("event-wheel",function(a,b,c){a=!1;try{WheelEvent("wheel"),a=!0}catch(d){}return a});var k="data-dgrid-column-set-id";B("safari","ie-7");var D=e("event-mousewheel")||e("event-wheel")?function(a){return function(b,c){return h(b,e("event-wheel")?"wheel":"mousewheel",function(d){var f=d.target;1!==f.nodeType&&(f=f.parentNode);for(;!n.matches(f,".dgrid-column-set["+k+"]",b);)if(f===b||!(f=f.parentNode))return;(d=d.deltaX||-d.wheelDeltaX/3)&&c.call(null,
a,f,d)})}}:function(a){return function(b,c){return h(b,".dgrid-column-set["+k+"]:MozMousePixelScroll",function(b){1===b.axis&&c.call(null,a,this,b.detail)})}};return y(null,{postCreate:function(){this.inherited(arguments);this.on(D(this),function(a,b,c){b=b.getAttribute(k);a=a._columnSetScrollers[b];c=a.scrollLeft+c;a.scrollLeft=0>c?0:c})},columnSets:[],createRowCells:function(a,b,c,d){for(var f=p("table.dgrid-row-table"),E=p(f,"tbody tr"),l=0,g=this.columnSets.length;l<g;l++){var m=p(E,a+".dgrid-column-set-cell.dgrid-column-set-"+
l+" div.dgrid-column-set["+k+"\x3d"+l+"]"),e;e=c||this.subRows;if(!e||!e.length)e=void 0;else{for(var h=[],n=l+"-",s=0,q=e.length;s<q;s++){var t=e[s],u=[];u.className=t.className;for(var v=0,r=t.length;v<r;v++){var w=t[v];null!=w.id&&0===w.id.indexOf(n)&&u.push(w)}h.push(u)}e=h}m.appendChild(this.inherited(arguments,[a,b,e||this.columnSets[l],d]))}return f},renderArray:function(){var a=this,b=this.inherited(arguments);z.when(b,function(b){for(var d=0;d<b.length;d++)C(a,b[d])});return b},renderHeader:function(){function a(){f._positionScrollers()}
this.inherited(arguments);var b=this.columnSets,c=this.domNode,d=this._columnSetScrollers;this._columnSetScrollerContents={};this._columnSetScrollLefts={};var f=this,e;if(d)for(e in d)p(d[e],"!");else r.after(this,"resize",a,!0),r.after(this,"styleColumn",a,!0),h(c,".dgrid-column-set:dgrid-cellfocusin",q.hitch(this,"_onColumnSetScroll"));d=this._columnSetScrollers={};e=0;for(c=b.length;e<c;e++)this._putScroller(b[e],e);this._positionScrollers()},styleColumnSet:function(a,b){var c=this.addCssRule("#"+
A.escapeCssIdentifier(this.domNode.id)+" .dgrid-column-set-"+a,b);this._positionScrollers();return c},_destroyColumns:function(){var a=this.columnSets.length,b,c,d,e,k,l,g,m;for(b=0;b<a;b++){l=this.columnSets[b];c=0;for(e=l.length;c<e;c++){g=l[c];d=0;for(k=g.length;d<k;d++)m=g[d],"function"===typeof m.destroy&&m.destroy()}}this.inherited(arguments)},configStructure:function(){this.columns={};this.subRows=[];for(var a=0,b=this.columnSets.length;a<b;a++)for(var c=this.columnSets[a],d=0;d<c.length;d++)c[d]=
this._configColumns(a+"-"+d+"-",c[d]);this.inherited(arguments)},_positionScrollers:function(){var a=this.domNode,b=this._columnSetScrollers,c=this._columnSetScrollerContents,d=this.columnSets,f=0,h=0,l=0,g,m;g=0;for(d=d.length;g<d;g++)f+=h,m=n(".dgrid-column-set["+k+'\x3d"'+g+'"]',a)[0],h=m.offsetWidth,m=m.firstChild.offsetWidth,c[g].style.width=m+"px",b[g].style.width=h+"px",b[g].style.bottom=this.showFooter?this.footerNode.offsetHeight+"px":"0px",b[g].style.overflowX=m>h?"scroll":"auto",b[g].style.left=
f+"px",m>h&&l++;this.bodyNode.style.bottom=l?e("dom-scrollbar-height")+(e("ie")?1:0)+"px":"0"},_putScroller:function(a,b){var c=this._columnSetScrollers[b]=p(this.domNode,"div.dgrid-column-set-scroller.dgrid-column-set-scroller-"+b+"["+k+"\x3d"+b+"]");this._columnSetScrollerContents[b]=p(c,"div.dgrid-column-set-scroller-content");h(c,"scroll",q.hitch(this,"_onColumnSetScroll"))},_onColumnSetScroll:function(a){var b=a.target.scrollLeft;a=a.target.getAttribute(k);var c;this._columnSetScrollLefts[a]!=
b&&(n(".dgrid-column-set["+k+'\x3d"'+a+'"],.dgrid-column-set-scroller['+k+'\x3d"'+a+'"]',this.domNode).forEach(function(a,e){a.scrollLeft=b;e||(c=a.scrollLeft)}),this._columnSetScrollLefts[a]=c)},_setColumnSets:function(a){this._destroyColumns();this.columnSets=a;this._updateColumns()},setColumnSets:function(a){x.deprecated("setColumnSets(...)",'use set("columnSets", ...) instead',"dgrid 0.4");this.set("columnSets",a)}})});
//@ sourceMappingURL=ColumnSet.js.map