//>>built
define("dgrid/editor","dojo/_base/kernel dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/on dojo/aspect dojo/has dojo/query ./Grid put-selector/put dojo/_base/sniff".split(" "),function(C,w,D,x,k,q,s,E,y,r){function u(a,b){a.value=b;if("radio"==a.type||"checkbox"==a.type)a.checked=a.defaultChecked=!!b}function z(a,b){if("number"==typeof b)a=isNaN(a)?a:parseFloat(a);else if("boolean"==typeof b)a="true"==a?!0:"false"==a?!1:a;else if(b instanceof Date){var c=new Date(a);a=isNaN(c.getTime())?
a:c}return a}function F(a,b,c,d,g){var e,f,h;if((c&&c.valueOf())!=(d&&d.valueOf())&&(e=b.element,f=b.row,h=b.column,h.field&&f))if(b={grid:a,cell:b,rowId:f.id,oldValue:c,value:d,bubbles:!0,cancelable:!0},g&&g.type&&(b.parentType=g.type),k.emit(e,"dgrid-datachange",b))a.updateDirty?(a.updateDirty(f.id,h.field,d),h.autoSave&&setTimeout(function(){a._trackError("save")},0)):f.data[h.field]=d;else{var l;(l=e.widget)?(l._dgridIgnoreChange=!0,l.set("value",c),setTimeout(function(){l._dgridIgnoreChange=
!1},0)):(l=e.input)&&u(l,c);return c}return d}function v(a,b,c){var d=a.cell(b.domNode||b),g=d.column,e;if(!b.isValid||b.isValid())if(c=F(a,d,n?p:b._dgridLastValue,"function"==typeof b.get?z(b.get("value")):z(b["checkbox"==b.type||"radio"==b.type?"checked":"value"]),c),n?p=c:b._dgridLastValue=c,"radio"===b.type&&b.name&&!g.editOn&&g.field)for(e in c=a.row(b),E("input[type\x3dradio][name\x3d"+b.name+"]",a.contentNode).forEach(function(c){var d=a.row(c);c!==b&&c._dgridLastValue&&(c._dgridLastValue=
!1,a.updateDirty?a.updateDirty(d.id,g.field,!1):d.data[g.field]=!1)}),a.dirty)c.id!==e&&a.dirty[e][g.field]&&a.updateDirty(e,g.field,!1)}function A(a){var b=a.editor,c=a.editOn,d=a.grid,g="string"!=typeof b,e,f,h;e=a.editorArgs||{};"function"==typeof e&&(e=e.call(d,a));if(g)f=new b(e),a=f.focusNode||f.domNode,a.className+=" dgrid-input",f.connect(f,c?"onBlur":"onChange",function(){f._dgridIgnoreChange||v(d,this,{type:"widget"})});else if(h=function(a){var b=a.target;"_dgridLastValue"in b&&-1<b.className.indexOf("dgrid-input")&&
v(d,b,a)},a.grid._hasInputListener||(d._hasInputListener=!0,d.on("change",function(a){h(a)})),f=a=r(("textarea"==b?"textarea":"input[type\x3d"+b+"]")+".dgrid-input",w.mixin({name:a.field,tabIndex:isNaN(a.tabIndex)?-1:a.tabIndex},e)),9>s("ie")||s("ie")&&s("quirks"))"radio"==b||"checkbox"==b?k(f,"click",function(a){h(a)}):k(f,"change",function(a){h(a)});return f}function G(a,b){function c(){var a=n;h.blur();"function"===typeof g.focus&&setTimeout(function(){g.focus(a)},e&&9>s("ie")?15:0)}var d=A(a),
g=a.grid,e=d.domNode,f=d.domNode||d,h=d.focusNode||f,l=e?function(){d.set("value",d._dgridLastValue)}:function(){u(d,d._dgridLastValue);v(a.grid,d)};k(h,"keydown",function(b){b=b.keyCode||b.which;27==b?(l(),p=d._dgridLastValue,c()):13==b&&!1!==a.dismissOnEnter&&c()});(a._editorBlurHandle=k.pausable(d,"blur",function(){var b=f.parentNode,c=b.children.length-1,h={alreadyHooked:!0},e=g.cell(f);k.emit(e.element,"dgrid-editor-hide",{grid:g,cell:e,column:a,editor:d,bubbles:!0,cancelable:!1});a._editorBlurHandle.pause();
b.removeChild(f);for(r(e.element,"!dgrid-cell-editing");c--;)r(b.firstChild,"!");y.appendIfNode(b,a.renderCell(a.grid.row(b).data,p,b,t?w.delegate(h,t):h));n=p=t=m=null})).pause();return d}function B(a,b,c,d){var g=a.domNode,e=b.grid;g||u(a,d);c.innerHTML="";r(c,".dgrid-cell-editing");r(c,a.domNode||a);g&&(a._started||a.startup(),a._dgridIgnoreChange=!0,a.set("value",d),setTimeout(function(){a._dgridIgnoreChange=!1},0));a._dgridLastValue=d;n&&(p=d,k.emit(c,"dgrid-editor-show",{grid:e,cell:e.cell(c),
column:b,editor:a,bubbles:!0,cancelable:!1}))}function H(a){var b,c,d,g,e,f,h;a.column||(a=this.cell(a));if(!a||!a.element)return null;c=a.column;e=c.field;d=a.element.contents||a.element;if(f=c.editorInstance){if(n!=d&&(b=a.row,b=(g=this.dirty&&this.dirty[b.id])&&e in g?g[e]:c.get?c.get(b.data):b.data[e],!c.canEdit||c.canEdit(a.row.data,b)))return n=d,B(c.editorInstance,c,d,b),h=new x,setTimeout(function(){f.focus&&f.focus();c._editorBlurHandle&&c._editorBlurHandle.resume();h.resolve(f)},0),h.promise}else if(c.editor&&
(f=d.widget||d.input))return h=new x,f.focus&&f.focus(),h.resolve(f),h.promise;return null}var n,p,t,m;return function(a,b,c){function d(a){var b=a.grid,c;b.edit||(b.edit=H,e.push(k(b.domNode,".dgrid-input:focusin",function(){m=b.cell(this)})),c=b._editorFocusoutHandle=k.pausable(b.domNode,".dgrid-input:focusout",function(){m=null}),e.push(c),e.push(q.before(b,"removeRow",function(a){a=b.row(a);m&&m.row.id===a.id&&(c.pause(),setTimeout(function(){c.resume()},0))})),e.push(q.after(b,"insertRow",function(a){var c=
b.row(a);m&&m.row.id===c.id&&b.edit(b.cell(c,m.column.id));return a})))}var g=a.renderCell||y.defaultRenderCell,e=[],f;a||(a={});a.editor=b=b||a.editor||"text";a.editOn=c=c||a.editOn;f="string"!=typeof b;a.widgetArgs&&(C.deprecated("column.widgetArgs","use column.editorArgs instead","dgrid 0.4"),a.editorArgs=a.widgetArgs);q.after(a,"init",c?function(){d(a);a.editorInstance=G(a,g)}:function(){var b=a.grid;d(a);f&&e.push(q.before(b,"removeRow",function(c){if(c=(c=b.cell(c,a.id).element)&&(c.contents||
c).widget)b._editorFocusoutHandle.pause(),c.destroyRecursive()}))});q.after(a,"destroy",function(){D.forEach(e,function(a){a.remove()});a._editorBlurHandle&&a._editorBlurHandle.remove();c&&f&&a.editorInstance.destroyRecursive();a.grid.edit=null});a.renderCell=c?function(b,d,e,f){if(!f||!f.alreadyHooked)k("TD"==e.tagName?e:e.parentNode,c,function(){t=f;a.grid.edit(this)});return g.call(a,b,d,e,f)}:function(b,c,d,e){if(!a.canEdit||a.canEdit(b,c))b=A(a),B(b,a,d,c),d[f?"widget":"input"]=b;else return g.call(a,
b,c,d,e)};return a}});
//@ sourceMappingURL=editor.js.map