//>>built
define("dgrid/OnDemandList","./List ./_StoreMixin dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/dom dojo/on ./util/misc put-selector/put".split(" "),function(F,G,H,C,s,I,t,u,q){return H([F,G],{minRowsPerPage:25,maxRowsPerPage:250,maxEmptySpace:Infinity,bufferRows:10,farOffRemoval:2E3,queryRowsOverlap:0,pagingMethod:"debounce",pagingDelay:u.defaultDelay,keepScrollPosition:!1,rowHeight:22,postCreate:function(){this.inherited(arguments);var c=this;t(this.bodyNode,"scroll",u[this.pagingMethod](function(d){c._processScroll(d)},
null,this.pagingDelay))},renderQuery:function(c,d,g){function k(b){q(v,"!");if(b)throw a._refreshDeferred&&(a._refreshDeferred.reject(b),delete a._refreshDeferred),b;}var a=this,h={query:c,count:0,node:d,options:g},l=this.preload,f;if(!d){var b={node:q(this.contentNode,"div.dgrid-preload",{rowIndex:0}),count:0,query:c,next:h,options:g};b.node.style.height="0";h.node=d=q(this.contentNode,"div.dgrid-preload");h.previous=b}d.rowIndex=this.minRowsPerPage;l?((h.next=l.next)&&d.offsetTop>=l.node.offsetTop?
h.previous=l:(h.next=l,h.previous=l.previous),h.previous.next=h,h.next.previous=h):this.preload=h;var v=q(d,"-div.dgrid-loading");q(v,"div.dgrid-below").innerHTML=this.loadingMessage;g=C.mixin(this.get("queryOptions"),g,{start:0,count:this.minRowsPerPage},"level"in c?{queryLevel:c.level}:null);this._trackError(function(){return f=c(g)});if("undefined"===typeof f)k();else return s.when(a.renderArray(f,d,g),function(b){return s.when("undefined"===typeof f.total?f.length:f.total,function(c){var k=b.length,
l=d.parentNode,p=a.noDataNode;q(v,"!");"queryLevel"in g||(a._total=c);0===c&&(p&&(q(p,"!"),delete a.noDataNode),a.noDataNode=p=q("div.dgrid-no-data"),l.insertBefore(p,a._getFirstRowSibling(l)),p.innerHTML=a.noDataMessage);for(p=l=0;p<k;p++)l+=a._calcRowHeight(b[p]);k&&l&&(a.rowHeight=l/k);c-=k;h.count=c;d.rowIndex=k;c?d.style.height=Math.min(c*a.rowHeight,a.maxEmptySpace)+"px":(d.style.display="none",g.count++);a._previousScrollPosition&&(a.scrollTo(a._previousScrollPosition),delete a._previousScrollPosition);
a._processScroll();a._refreshDeferred&&(a._refreshDeferred.resolve(f),delete a._refreshDeferred);return b},k)},k),f},refresh:function(c){var d=this,g=c&&c.keepScrollPosition,k;"undefined"===typeof g&&(g=this.keepScrollPosition);g&&(this._previousScrollPosition=this.getScrollPosition());this.inherited(arguments);if(this.store)return g=this._refreshDeferred=new s,k=d.renderQuery(function(a){return d.store.query(d.query,a)}),"undefined"===typeof k&&g.reject(),g.then(function(a){setTimeout(function(){t.emit(d.domNode,
"dgrid-refresh-complete",{bubbles:!0,cancelable:!1,grid:d,results:a})},0);delete d._refreshDeferred;return a},function(a){delete d._refreshDeferred;throw a;})},resize:function(){this.inherited(arguments);this._processScroll()},_getFirstRowSibling:function(c){return c.lastChild},_calcRowHeight:function(c){var d=c.previousSibling;return d&&!/\bdgrid-preload\b/.test(d.className)?c.offsetTop-d.offsetTop:c.offsetHeight},lastScrollTop:0,_processScroll:function(c){function d(b,c,d,k){var f=a.farOffRemoval,
h=b.node;if(c>2*f){for(var e,l=h[d],m=0,n=0,p=[];e=l;){var r=a._calcRowHeight(e);if(m+r+f>c||0>l.className.indexOf("dgrid-row")&&0>l.className.indexOf("dgrid-loading"))break;l=e[d];m+=r;n+=e.count||1;a.removeRow(e,!0);p.push(e)}b.count+=n;k?(h.rowIndex-=n,g(b)):h.style.height=h.offsetHeight+m+"px";var s=q("div",p);setTimeout(function(){q(s,"!")},1)}}function g(b,c){b.node.style.height=Math.min(b.count*a.rowHeight,c?Infinity:a.maxEmptySpace)+"px"}function k(a,b){do a=b?a.next:a.previous;while(a&&!a.node.offsetWidth);
return a}var a=this,h=a.bodyNode;c=c&&c.scrollTop||this.getScrollPosition().y;var h=h.offsetHeight+c,l,f,b=a.preload,v=a.lastScrollTop,A=a.bufferRows*a.rowHeight,t=A-a.rowHeight,u,D,p,B=!0;for(a.lastScrollTop=c;b&&!b.node.offsetWidth;)b=b.previous;for(;b&&b!=l;){l=a.preload;a.preload=b;f=b.node;var e=f.offsetTop;if(h+1+t<e)b=k(b,B=!1);else if(c-1-t>e+f.offsetHeight)b=k(b,B=!0);else{var m=((f.rowIndex?c-A:h)-e)/a.rowHeight,e=(h-c+2*A)/a.rowHeight,y=Math.max(Math.min((c-v)*a.rowHeight,a.maxRowsPerPage/
2),a.maxRowsPerPage/-2),e=e+Math.min(Math.abs(y),10);0==f.rowIndex&&(m-=e);m=Math.max(m,0);10>m&&(0<m&&e+m<a.maxRowsPerPage)&&(e+=Math.max(0,m),m=0);e=Math.min(Math.max(e,a.minRowsPerPage),a.maxRowsPerPage,b.count);if(0==e)b=k(b,B);else{var e=Math.ceil(e),m=Math.min(Math.floor(m),b.count-e),n=C.mixin(a.get("queryOptions"),b.options);b.count-=e;var r=f,z,w=a.queryRowsOverlap;if(y=0<f.rowIndex&&b){var x=b.previous;x&&(d(x,c-(x.node.offsetTop+x.node.offsetHeight),"nextSibling"),0<m&&x.node==f.previousSibling?
(m=Math.min(b.count,m),b.previous.count+=m,g(b.previous,!0),f.rowIndex+=m,w=0):e+=m,b.count-=m);n.start=f.rowIndex-w;n.count=Math.min(e+w,a.maxRowsPerPage);f.rowIndex=n.start+n.count}else b.next&&(d(b.next,b.next.node.offsetTop-h,"previousSibling",!0),r=f.nextSibling,r==b.next.node?(b.next.count+=b.count-m,b.next.node.rowIndex=m+e,g(b.next),b.count=m,w=0):z=!0),n.start=b.count,n.count=Math.min(e+w,a.maxRowsPerPage);z&&(r&&r.offsetWidth)&&(z=r.offsetTop);g(b);"level"in b.query&&(n.queryLevel=b.query.level);
if("queryLevel"in n||!(n.start>a._total||0>n.count)){f=q(r,"-div.dgrid-loading[style\x3dheight:"+e*a.rowHeight+"px]");q(f,"div.dgrid-"+(y?"below":"above")).innerHTML=a.loadingMessage;f.count=e;var E=b.query(n);if(void 0===a._trackError(function(){return E})){q(f,"!");return}(function(b,c,d,e){p=s.when(a.renderArray(e,b,n),function(h){D=e;r=b.nextSibling;q(b,"!");if(d&&r&&r.offsetWidth){var f=a.getScrollPosition();a.scrollTo({x:f.x,y:f.y+r.offsetTop-d,preserveMomentum:!0})}s.when(e.total||e.length,
function(b){"queryLevel"in n||(a._total=b);c&&(c.count=b-c.node.rowIndex,0===c.count&&n.count++,g(c))});a._processScroll();return h},function(a){q(b,"!");throw a;})}).call(this,f,y,z,E);b=b.previous}}}}if(p&&(u=this._refreshDeferred))delete this._refreshDeferred,s.when(p,function(){u.resolve(D)})},removeRow:function(c,d){if(c){var g=c.previousSibling,k=c.nextSibling,g=g&&(null!=g.observerIndex?g.observerIndex:g.previousObserverIndex),a=k&&(null!=k.observerIndex?k.observerIndex:k.nextObserverIndex),
k=c.observerIndex;c.observerIndex=void 0;d&&(c.nextObserverIndex=a,c.previousObserverIndex=g);if(this.cleanEmptyObservers&&(-1<k&&k!==g&&k!==a)&&(g=this.observers,a=g[k])){if(!d)for(var h=a.rows,l=0;l<h.length;l++)if(h[l]!=c&&I.isDescendant(h[l],this.domNode))return this.inherited(arguments);a.cancel();this._numObservers--;g[k]=0}}this.inherited(arguments)}})});
//@ sourceMappingURL=OnDemandList.js.map