//>>built
define("dgrid/tree","dojo/_base/declare dojo/_base/array dojo/_base/Deferred dojo/query dojo/on dojo/aspect ./util/has-css3 ./Grid dojo/has!touch?./util/touch put-selector/put".split(" "),function(C,y,z,r,A,f,u,B,v,m){function w(c,f,h,g){g=this.grid.isRTL?"right":"left";var b=".dgrid-expando-icon";f&&(b+=".ui-icon.ui-icon-triangle-1-"+(h?"se":"e"));c=m("div"+b+"[style\x3dmargin-"+g+": "+c*(this.indentWidth||9)+"px; float: "+g+"]");c.innerHTML="\x26nbsp;";return c}function x(c){var f=this,h=this.style.height;
h&&(this.style.display="0px"==h?"none":"block");c&&(m(this,".dgrid-tree-resetting"),setTimeout(function(){m(f,"!dgrid-tree-resetting")}));this.style.height=""}function n(c){var n=c.renderCell||B.defaultRenderCell,h,g;c||(c={});c.shouldExpand=c.shouldExpand||function(b,c,d){return d};f.after(c,"init",function(){var b=c.grid,p=".dgrid-content .dgrid-column-"+c.id,d=[];b.cleanEmptyObservers=!1;if(!b.store)throw Error("dgrid tree column plugin requires a store to operate.");c.renderExpando||(c.renderExpando=
w);d.push(b.on(c.expandOn||".dgrid-expando-icon:click,"+p+":dblclick,"+p+":keydown",function(a){var e=b.row(a);(!b.store.mayHaveChildren||b.store.mayHaveChildren(e.data))&&(("keydown"!=a.type||32==a.keyCode)&&!("dblclick"==a.type&&g&&1<g.count&&e.id==g.id&&-1<a.target.className.indexOf("dgrid-expando-icon")))&&b.expand(e);-1<a.target.className.indexOf("dgrid-expando-icon")&&(g&&g.id==b.row(a).id?g.count++:g={id:b.row(a).id,count:1})}));u("touch")&&d.push(b.on(v.selector(p,v.dbltap),function(){b.expand(this)}));
b._expanded||(b._expanded={});d.push(f.after(b,"insertRow",function(a){var b=this.row(a);c.shouldExpand(b,h,this._expanded[b.id])&&this.expand(a,!0,!0);return a}));d.push(f.before(b,"removeRow",function(a,c){var d=a.connected;d&&(r("\x3e.dgrid-row",d).forEach(function(a){b.removeRow(a,!0)}),c||m(d,"!"))}));c.collapseOnRefresh&&d.push(f.after(b,"cleanup",function(){this._expanded={}}));b._calcRowHeight=function(a){var b=a.connected;return a.offsetHeight+(b?b.offsetHeight:0)};b.expand=function(a,e,
d){var l=a.element?a:b.row(a),g=u("transitionend");a=new z;var f=a.promise;a.resolve();a=l.element;if((a=-1<a.className.indexOf("dgrid-expando-icon")?a:r(".dgrid-expando-icon",a)[0])&&a.mayHaveChildren&&(d||e!==!!this._expanded[l.id])){var h=void 0===e?!this._expanded[l.id]:e;m(a,".ui-icon-triangle-1-"+(h?"se":"e")+"!ui-icon-triangle-1-"+(h?"e":"se"));var p=a.preloadNode;e=l.element;var k,q,n,t={originalQuery:this.query};if(!p){k=e.connected=m("div.dgrid-tree-container");var p=a.preloadNode=m(e,"+",
k,"div.dgrid-preload"),s=function(a){return b.store.getChildren(l.data,a)};c.allowDuplicates&&(t.parentId=l.id);"level"in a&&(s.level=a.level);f=f.then(function(){return b.renderQuery?b.renderQuery(s,p,t):b.renderArray(s(t),p,"level"in s?{queryLevel:s.level}:{})}).then(function(){if(b._expanded[l.id]&&g){var a=k.scrollHeight;k.style.height=a?a+"px":"auto"}});g?A(k,g,x):x.call(k)}k=e.connected;k.hidden=!h;q=k.style;!g||d?(q.display=h?"block":"none",q.height=""):(h?(q.display="block",n=k.scrollHeight,
q.height="0px"):(m(k,".dgrid-tree-resetting"),q.height=k.scrollHeight+"px"),setTimeout(function(){m(k,"!dgrid-tree-resetting");q.height=h?n?n+"px":"auto":"0px"}));h?this._expanded[l.id]=!0:delete this._expanded[l.id]}return f};f.after(c,"destroy",function(){y.forEach(d,function(a){a.remove()});delete b.expand;delete b._calcRowHeight})});c.renderCell=function(b,g,d,a){var e=c.grid,f=Number(a&&a.queryLevel)+1,l=!e.store.mayHaveChildren||e.store.mayHaveChildren(b),r=a.parentId,f=h=isNaN(f)?0:f,e=c.renderExpando(f,
l,e._expanded[(r?r+"-":"")+e.store.getIdentity(b)],b);e.level=f;e.mayHaveChildren=l;(b=n.call(c,b,g,d,a))&&b.nodeType?(m(d,e),m(d,b)):d.insertBefore(e,d.firstChild)};return c}n.defaultRenderExpando=w;return n});
//@ sourceMappingURL=tree.js.map