//>>built
define("esri/layers/labelLayerUtils/StaticLabelClass","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/has dojox/gfx/_base ../../kernel ../../lang ../../SpatialReference ../GraphicsLayer ../LabelClass ../../renderers/SimpleRenderer ../../geometry/Geometry ../../geometry/Extent ../../geometry/Point ../../geometry/Polyline ../../geometry/Polygon ../../symbols/TextSymbol ../../symbols/ShieldLabelSymbol ../../symbols/SimpleLineSymbol".split(" "),function(A,C,D,E,F,G,H,I,B,J,K,L,y,M,N,z,O,P,
Q){return A(B,{declaredClass:"esri.layers.labelLayerUtils.StaticLabel",constructor:function(){this._preparedLabels=[];this._placedLabels=[];this._extent=null;this._ymax=this._ymin=this._xmax=this._xmin=0;this._scale=1;this._LINE_STEP_CONST=1.5;this._POLYGON_X_STEP_CONST=1;this._POLYGON_Y_STEP_CONST=0.75},setMap:function(c,b){this._labelLayer=b;this._map=c;this._xmin=c.extent.xmin;this._xmax=c.extent.xmax;this._ymin=c.extent.ymin;this._ymax=c.extent.ymax;this._scale=(this._xmax-this._xmin)/c.width},
_process:function(c){var b,d,e,a,f,k,g,m;this._preparedLabels=c;this._placedLabels=[];for(c=this._preparedLabels.length-1;0<=c;c--){b=this._preparedLabels[c];a=b.labelWidth;f=b.labelHeight;g=(k=b.options)&&void 0!==k.lineLabelPlacement?k.lineLabelPlacement:"PlaceAtCenter";m=k&&void 0!==k.lineLabelPosition?k.lineLabelPosition:"Above";d=k&&void 0!==k.labelRotation?k.labelRotation:!0;e=b.angle*(Math.PI/180);var l=[];if("point"===b.geometry.type)this._generatePointPositions(b.geometry.x,b.geometry.y,
b.text,e,a,f,b.symbolWidth,b.symbolHeight,k,l);else if("multipoint"===b.geometry.type)for(d=0;d<b.geometry.points.length;d++)this._generatePointPositions(b.geometry.points[d][0],b.geometry.points[d][1],b.text,e,a,f,b.symbolWidth,b.symbolHeight,k,l);else if("polyline"===b.geometry.type)"PlaceAtStart"===g?this._generateLinePositionsPlaceAtStart(b.geometry,b.text,a,f,2*b.symbolHeight+f,g,m,d,l):"PlaceAtEnd"===g?this._generateLinePositionsPlaceAtEnd(b.geometry,b.text,a,f,2*b.symbolHeight+f,g,m,d,l):this._generateLinePositionsPlaceAtCenter(b.geometry,
b.text,a,f,2*b.symbolHeight+f,g,m,d,l);else if("polygon"===b.geometry.type)for(d=0;d<b.geometry.rings.length;d++)k=b.geometry.rings[d],z.prototype.isClockwise(k)&&this._generatePolygonPositionsForManyLabels(k,b.geometry.spatialReference,b.text,e,a,f,l);for(d=0;d<l.length;d++)k=l[d].x,g=l[d].y,void 0!==l[d].angle&&(e=l[d].angle),this._findPlace(b,b.text,k,g,e,a,f)}return this._placedLabels},_generatePointPositions:function(c,b,d,e,a,f,k,g,m,l){d=m&&m.pointPriorities?m.pointPriorities:"AboveRight";
a=(k+a)*this._scale;f=(g+f)*this._scale;switch(d.toLowerCase()){case "aboveleft":c-=a;b+=f;break;case "abovecenter":b+=f;break;case "aboveright":c+=a;b+=f;break;case "centerleft":c-=a;break;case "centercenter":break;case "centerright":c+=a;break;case "belowleft":c-=a;b-=f;break;case "belowcenter":b-=f;break;case "belowright":c+=a;b-=f;break;default:return}l.push({x:c,y:b})},_generateLinePositionsPlaceAtStart:function(c,b,d,e,a,f,k,g,m){f=d*this._scale;var l=this._LINE_STEP_CONST*Math.min(this._map.width,
this._map.height)*this._scale,h,p,q,v,t,s,n,u;for(h=0;h<c.paths.length;h++){var r=c.paths[h],x=f,w=0;for(p=0;p<r.length-1;p++)q=r[p][0],v=r[p][1],t=r[p+1][0],s=r[p+1][1],n=t-q,u=s-v,n=Math.sqrt(n*n+u*u),w+n>x?(w=this._generatePositionsOnLine(c.spatialReference,x,l,w,q,v,t,s,b,d,e,a,k,g,m),x=l):w+=n}},_generateLinePositionsPlaceAtEnd:function(c,b,d,e,a,f,k,g,m){f=d*this._scale;var l=this._LINE_STEP_CONST*Math.min(this._map.width,this._map.height)*this._scale,h,p,q,v,t,s,n,u;for(h=0;h<c.paths.length;h++){var r=
c.paths[h],x=f,w=0;for(p=r.length-2;0<=p;p--)q=r[p+1][0],v=r[p+1][1],t=r[p][0],s=r[p][1],n=t-q,u=s-v,n=Math.sqrt(n*n+u*u),w+n>x?(w=this._generatePositionsOnLine(c.spatialReference,x,l,w,q,v,t,s,b,d,e,a,k,g,m),x=l):w+=n}},_generateLinePositionsPlaceAtCenter:function(c,b,d,e,a,f,k,g,m){f=this._LINE_STEP_CONST*Math.min(this._map.width,this._map.height)*this._scale;var l,h,p,q,v,t,s,n,u;for(l=0;l<c.paths.length;l++){var r=c.paths[l];if(!(2>r.length)){var x=0;for(h=0;h<r.length-1;h++)q=r[h][0],v=r[h][1],
t=r[h+1][0],s=r[h+1][1],n=t-q,u=s-v,x+=Math.sqrt(n*n+u*u);var w=0;for(h=0;h<r.length-1;h++){q=r[h][0];v=r[h][1];t=r[h+1][0];s=r[h+1][1];n=t-q;u=s-v;n=Math.sqrt(n*n+u*u);if(w+n>x/2)break;w+=n}h==r.length-1&&h--;q=r[h][0];v=r[h][1];t=r[h+1][0];s=r[h+1][1];n=t-q;u=s-v;w=x/2-w;u=Math.atan2(u,n);n=q+w*Math.cos(u);u=v+w*Math.sin(u);q=this._angleAndShifts(q,v,t,s,a,k,g);m.push({x:n+q.shiftX,y:u+q.shiftY,angle:q.angle});var x=n,y=u,w=0;for(p=h;p<r.length-1;p++)p==h?(q=x,v=y):(q=r[p][0],v=r[p][1]),t=r[p+1][0],
s=r[p+1][1],n=t-q,u=s-v,n=Math.sqrt(n*n+u*u),w=w+n>f?this._generatePositionsOnLine(c.spatialReference,f,f,w,q,v,t,s,b,d,e,a,k,g,m):w+n;w=0;for(p=h;0<=p;p--)p==h?(q=x,v=y):(q=r[p+1][0],v=r[p+1][1]),t=r[p][0],s=r[p][1],n=t-q,u=s-v,n=Math.sqrt(n*n+u*u),w=w+n>f?this._generatePositionsOnLine(c.spatialReference,f,f,w,q,v,t,s,b,d,e,a,k,g,m):w+n}}},_generatePositionsOnLine:function(c,b,d,e,a,f,k,g,m,l,h,p,q,v,t){m=Math.atan2(g-f,k-a);l=a;h=f;var s=l,n=h;do if(e=b-e,l+=e*Math.cos(m),h+=e*Math.sin(m),this._belongs(l,
h,a,f,k,g))e=this._angleAndShifts(a,f,k,g,p,q,v),b=l+e.shiftX,n=h+e.shiftY,this._labelLayer._isWithinScreenArea(new y(b,n,b,n,c))&&t.push({x:b,y:n,angle:e.angle}),s=l,n=h,e=0,b=d;else return c=k-s,g-=n,Math.sqrt(c*c+g*g);while(1)},_belongs:function(c,b,d,e,a,f){if(a==d&&f==e)return!1;if(a>d){if(c>a||c<d)return!1}else if(c<a||c>d)return!1;if(f>e){if(b>f||b<e)return!1}else if(b<f||b>e)return!1;return!0},_angleAndShifts:function(c,b,d,e,a,f,k){for(c=Math.atan2(e-b,d-c);c>Math.PI/2;)c-=Math.PI;for(;c<
-(Math.PI/2);)c+=Math.PI;e=Math.sin(c);var g=Math.cos(c);d=b=0;"Above"==f&&(b=a*e*this._scale,d=a*g*this._scale);"Below"==f&&(b=-a*e*this._scale,d=-a*g*this._scale);a=[];a.angle=k?-c:0;a.shiftX=-b;a.shiftY=d;return a},_generatePolygonPositionsForManyLabels:function(c,b,d,e,a,f,k){e=this._calcRingExtent(c);if(0.75*(e.xmax-e.xmin)>this._map.width*this._scale||0.75*(e.ymax-e.ymin)>this._map.height*this._scale){var g=this._findCentroidForRing(c);f=this._map.width*this._scale<e.xmax-e.xmin?this._POLYGON_X_STEP_CONST*
this._map.width*this._scale:this._POLYGON_X_STEP_CONST*(e.xmax-e.xmin);a=this._map.height*this._scale<e.ymax-e.ymin?this._POLYGON_Y_STEP_CONST*this._map.height*this._scale:this._POLYGON_Y_STEP_CONST*(e.ymax-e.ymin);var m=g[0]-Math.round((g[0]-e.xmin)/f)*f,l=g[1]-Math.round((g[1]-e.ymin)/a)*a,h,g=!0;for(h=l;h<e.ymax;h+=a)if(g=!g,!(h<this._ymin||h>this._ymax))for(l=m+(g?0:f/2);l<e.xmax;l+=f)this._labelLayer._isWithinScreenArea(new y(l,h,l,h,b))&&this._isPointWithinRing(d,c,l,h)&&k.push({x:l,y:h})}else{g=
this._findCentroidForRing(c);for(e=0;10>e;e++)if(a=g[0],m=g[1]+(e%2?-1:1)*Math.floor(e/2)*f*this._scale,this._labelLayer._isWithinScreenArea(new y(a,m,a,m,b))&&this._isPointWithinRing(d,c,a,m)){k.push({x:a,y:m});break}}},_calcRingExtent:function(c){var b,d;d=new y;for(b=0;b<c.length-1;b++){var e=c[b][0],a=c[b][1];if(void 0===d.xmin||e<d.xmin)d.xmin=e;if(void 0===d.ymin||a<d.ymin)d.ymin=a;if(void 0===d.xmax||e>d.xmax)d.xmax=e;if(void 0===d.ymax||a>d.ymax)d.ymax=a}return d},_isPointWithinPolygon:function(c,
b,d,e){var a;for(a=0;a<b.rings.length;a++)if(this._isPointWithinRing(c,b.rings[a],d,e))return!0;return!1},_isPointWithinRing:function(c,b,d,e){var a,f,k,g,m=[],l=b.length;for(c=0;c<l-1;c++)if(a=b[c][0],f=b[c][1],k=b[c+1][0],g=b[c+1][1],!(a==k&&f==g)){if(f==g)if(e==f)m.push(a);else continue;a==k?(f<g&&e>=f&&e<g&&m.push(a),f>g&&e<=f&&e>g&&m.push(a)):(f=(k-a)/(g-f)*(e-f)+a,a<k&&f>=a&&f<k&&m.push(f),a>k&&f<=a&&f>k&&m.push(f))}m.sort(function(a,b){return a-b});for(c=0;c<m.length-1;c++)if(a=m[c],k=m[c+
1],d>=a&&d<k)if(c%2)break;else return!0;return!1},_findCentroidForRing:function(c){for(var b=c.length,d=[0,0],e=0,a=c[0][0],f=c[0][1],k=1;k<b-1;k++){var g=c[k][0],m=c[k][1],l=c[k+1][0],h=c[k+1][1],p=(g-a)*(h-f)-(l-a)*(m-f);d[0]+=p*(a+g+l);d[1]+=p*(f+m+h);e+=p}d[0]/=3*e;d[1]/=3*e;return d},_findCentroidForFeature:function(c){for(var b=0,d=[0,0],e=0;e<c.rings.length;e++)for(var a=c.rings[e],f=a.length,k=a[0][0],g=a[0][1],m=1;m<f-1;m++){var l=a[m][0],h=a[m][1],p=a[m+1][0],q=a[m+1][1],v=(l-k)*(q-g)-(p-
k)*(h-g);d[0]+=v*(k+l+p);d[1]+=v*(g+h+q);b+=v}d[0]/=3*b;d[1]/=3*b;return d},_findPlace:function(c,b,d,e,a,f,k){if(isNaN(d)||isNaN(e))return!1;for(var g=0;g<this._placedLabels.length;g++){var m=this._placedLabels[g].angle,l=this._placedLabels[g].width*this._scale,h=this._placedLabels[g].height*this._scale,p=this._placedLabels[g].x-d,q=this._placedLabels[g].y-e;if(0===a&&0===m){if(this._findPlace2(-f*this._scale,-k*this._scale,f*this._scale,k*this._scale,p-l,q-h,p+l,q+h))return!1}else{var v=new y(-f*
this._scale,-k*this._scale,f*this._scale,k*this._scale,null),t=0,s=1;0!==a&&(t=Math.sin(a),s=Math.cos(a));var n=p*s-q*t,p=p*t+q*s,m=m-a,t=Math.sin(m),s=Math.cos(m),u=-l*s- -h*t,q=-l*t+-h*s,m=+l*s- -h*t,r=+l*t+-h*s,l=n+u,h=p-q,t=n+m,s=p-r,u=n-u,q=p+q,n=n-m,p=p+r,m=new z;m.addRing([[l,h],[t,s],[u,q],[n,p],[l,h]]);if(v.intersects(m))return!1}}for(;a>Math.PI/2;)a-=Math.PI;for(;a<-(Math.PI/2);)a+=Math.PI;g={};g.layer=c;g.text=b;g.angle=a;g.x=d;g.y=e;g.width=f;g.height=k;this._placedLabels.push(g);return!0},
_findPlace2:function(c,b,d,e,a,f,k,g){return(c>=a&&c<=k||d>=a&&d<=k||c<=a&&d>=k)&&(b>=f&&b<=g||e>=f&&e<=g||b<=f&&e>=g)?!0:!1}})});
//@ sourceMappingURL=StaticLabelClass.js.map