//>>built
define("bootstrap-map-js/js/bootstrapmap","esri/map esri/arcgis/utils esri/geometry/Point dojo/_base/declare dojo/on dojo/touch dojo/dom dojo/_base/lang dojo/dom-style dojo/query dojo/NodeList-traverse dojo/dom-class dojo/domReady!".split(" "),function(n,p,l,q,e,r,s,d,m,g,u,t){return{create:function(a,b){var c,f;if(a&&b)return c=new this._smartResizer(a,b),f=c.createMap(),f._smartResizer=c,f},createWebMap:function(a,b,c){if(b&&c)return b=new this._smartResizer(b,c),a=b.createWebMap(a)},destroy:function(a){if(a&&
a._smartResizer&&(a=a._smartResizer,a._handles))for(var b=a._handles.length;b--;)a._handles[b].remove(),a._handles.splice(b,1)},_smartResizer:q(null,{constructor:function(a,b){this._map=null;this._autoRecenterDelay=50;this._popupRecenterDelayer=150;this._popupPosition="top";this._popupBlocked=!1;this._visible=!0;this._mapDeferred=this._visibilityTimer=null;this._autoRecenter=b.autoRecenter||!0;this._responsiveResize=b.responsiveResize||!0;this._mapDivId=a;this._mapDiv=s.byId(a);this._mapStyle=m.get(this._mapDiv);
this._options=d.mixin(b,{});this._handles=[]},createMap:function(){this._setMapDiv(!1);this._responsiveResize&&d.mixin(this._options,{smartNavigation:!1,autoResize:!1});this._map=new n(this._mapDivId,this._options);this._setPopup();this._bindEvents();return this._mapDiv.__map=this._map},createWebMap:function(a){var b;this._setMapDiv(!1);this._options.hasOwnProperty("mapOptions")||(this._options.mapOptions={});this._responsiveResize&&d.mixin(this._options.mapOptions,{smartNavigation:!1,autoResize:!1});
this._mapDeferred=a=p.createMap(a,this._mapDivId,this._options);b=this;this._mapDeferred.then(d.hitch(this,function(a){this._map=a.map;this._setPopup();this._bindEvents();this._mapDiv.__map=this._map;this._smartResizer=b}));return a},_setPopup:function(){t.add(this._map.infoWindow.domNode,"light")},_setTouchBehavior:function(){this._options.hasOwnProperty("scrollWheelZoom")?this._options.scrollWheelZoom?this._map.enableScrollWheelZoom():this._map.disableScrollWheelZoom():this._map.disableScrollWheelZoom();
e(g(".esriPopup .titleButton.close"),r.press,d.hitch(this,function(){this._map.infoWindow.hide()}))},_bindEvents:function(){var a,b,c;this._map&&(a=function(){this._setTouchBehavior()},this._map.loaded?d.hitch(this,a).call():this._handles.push(e(this._map,"load",d.hitch(this,a))),a=function(){this._map.infoWindow.anchor=this._popupPosition;var a=function(a){var b=a._map.infoWindow.location;b&&!a._popupBlocked&&(a._popupBlocked=!0,window.setTimeout(function(){a._repositionMapForInfoWin(b);a._popupBlocked=
!1},a._popupRecenterDelayer))};this.counter=0;this._map.on("click",d.hitch(this,function(){this._map.infoWindow.isShowing&&a(this)}));e(this._map.graphics,"click",d.hitch(this,function(){a(this)}));e(this._map.infoWindow,"show",d.hitch(this,function(){a(this)}))},this._map.loaded?d.hitch(this,a).call():this._handles.push(e(this._map,"load",d.hitch(this,a))),a=function(a,c,d){return function(){var e=this,k=arguments;b?clearTimeout(b):d&&a.apply(e,k);b=setTimeout(function(){d||a.apply(e,k);b=null},
c||100)}},a=a(this._setMapDiv,100,!1),this._handles.push(e(window,"resize",d.hitch(this,a))),this._autoRecenter&&this._handles.push(e(this._map,"resize",d.hitch(this,function(){this._map.__resizeCenter=this._map.extent.getCenter();c=function(){this._map.centerAt(this._map.__resizeCenter)};setTimeout(d.hitch(this,c),this._autoRecenterDelay)}))))},_getMapDivVisibility:function(){return 0<this._mapDiv.clientHeight||0<this._mapDiv.clientWidth},_checkVisibility:function(){var a=this._getMapDivVisibility();
this._visible!==a&&a&&this._setMapDiv(!0)},_controlVisibilityTimer:function(a){a?this._visibilityTimer=setInterval(d.hitch(this,function(){this._checkVisibility()}),200):this._visibilityTimer&&(clearInterval(this._visibilityTimer),this._visibilityTimer=null)},_setMapDiv:function(a){if(this._mapDivId&&this._responsiveResize){var b,c,f,d;b=this._getMapDivVisibility();this._visible!==b&&(this._visible=b,this._controlVisibilityTimer(!b));this._visible&&(b=document.documentElement.clientHeight,c=document.body.clientHeight,
b-=c,c=this._calcMapHeight(),f=this._calcColumnHeight(c),d=c+b,m.set(this._mapDivId,{height:(c<f?0<b?f+b:f:d<f?f:d)+"px",width:"auto"}),this._map&&(a&&this._visible)&&(this._map.resize(),this._map.reposition()))}},_calcMapHeight:function(){var a=this._mapStyle,b=parseInt(a.paddingTop,10)+parseInt(a.paddingBottom,10)||0,c=parseInt(a.marginTop,10)+parseInt(a.marginBottom,10)||0,a=parseInt(a.borderTopWidth,10)+parseInt(a.borderBottomWidth,10)||0;return b+c+a+this._mapDiv.clientHeight},_calcColumnHeight:function(a){var b,
c=0,d=g(this._mapDiv).closest(".row").children("[class*\x3d'col']"),e;if(d.length)for(a=0;a<d.length;a++)b=d[a],e=0<g("#"+this._mapDivId,b).length,b.clientHeight>c&&!e&&(c=b.clientHeight);return c},_repositionMapForInfoWin:function(a){var b=new l(this._map.extent.xmax,this._map.extent.ymax,this._map.spatialReference),c=new l(this._map.extent.getCenter()),b=this._map.toScreen(b),c=this._map.toScreen(c),d=this._map.toScreen(a),e=this._map.infoWindow.domNode.childNodes[0],h=e.clientWidth;a=d.x-h/2;var h=
d.x+h/2,g=0>a-10,k=h>b.x-10,d=d.y-(e.clientHeight+this._map.infoWindow.marginTop)-this._map.infoWindow.offsetY,e=0>d-3;g?c.x-=10>Math.abs(a)+10?10:Math.abs(a)+10:k&&(c.x+=h-b.x+10);e&&(c.y+=d-3);if(k||g||e)c=this._map.toMap(c),this._map.centerAt(c)}})}});
//@ sourceMappingURL=bootstrapmap.js.map