//>>built
define("esri/arcgis/csv","dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/sniff dojo/number dojox/data/CsvStore ../kernel ../config ../request ../SpatialReference ../geometry/Geometry ../geometry/jsonUtils ../geometry/webMercatorUtils".split(" "),function(h,d,y,J,K,L,N,z,M,p,O,A,B){function C(a){var b=0,c="";d.forEach([","," ",";","|","\t"],function(f){var e=a.split(f).length;e>b&&(b=e,c=f)});return c}function D(a,b){if(!a||"[object Date]"!==Object.prototype.toString.call(a)||isNaN(a.getTime()))return!1;
var c=!0;if(J("chrome")&&/\d+\W*$/.test(b)){var f=b.match(/[a-zA-Z]{2,}/);if(f){for(var c=!1,e=0,l=f.length,d=/^((jan(uary)?)|(feb(ruary)?)|(mar(ch)?)|(apr(il)?)|(may)|(jun(e)?)|(jul(y)?)|(aug(ust)?)|(sep(tember)?)|(oct(ober)?)|(nov(ember)?)|(dec(ember)?)|(am)|(pm)|(gmt)|(utc))$/i;!c&&e<=l&&!(c=!d.test(f[e]));)e++;c=!c}}return c}function E(a,b,c){var f=a.indexOf("\n"),f=h.trim(a.substr(0,f)),e=b.columnDelimiter;e||(e=C(f));var l=new L({data:a,separator:e});l.fetch({onComplete:function(a,f){var g=
0,e={layerDefinition:b.layerDefinition,featureSet:{features:[],geometryType:"esriGeometryPoint"}},v=e.layerDefinition.objectIdField;!v&&!d.some(e.layerDefinition.fields,function(a){return"esriFieldTypeOID"==a.type?(v=a.name,!0):!1})&&(e.layerDefinition.fields.push({name:"__OBJECTID",alias:"__OBJECTID",type:"esriFieldTypeOID",editable:!1,domain:null}),v="__OBJECTID");var h,n,q=l._attributes,p=[],r=[];d.forEach(e.layerDefinition.fields,function(a,g){"esriFieldTypeDate"===a.type?p.push(a.name):("esriFieldTypeDouble"===
a.type||"esriFieldTypeInteger"===a.type)&&r.push(a.name)});b.locationInfo&&"coordinates"===b.locationInfo.locationType?(h=b.locationInfo.latitudeFieldName,n=b.locationInfo.longitudeFieldName):d.forEach(q,function(a){var g;g=d.indexOf(F,a.toLowerCase());-1!==g&&(h=a);g=d.indexOf(G,a.toLowerCase());-1!==g&&(n=a)},this);if(!h||!n)setTimeout(function(){},1),c&&c(null,Error("File does not seem to contain fields with point coordinates."));else{-1===d.indexOf(r,h)&&r.push(h);-1===d.indexOf(r,n)&&r.push(n);
var q=0,u=a.length;for(q;q<u;q++){var s=a[q],t=l.getAttributes(s),m={};d.forEach(t,function(a,g){if(a){var b=a;0===a.length&&d.forEach(e.layerDefinition.fields,function(g,b){g.name==="attribute_"+(b-1)&&(a="attribute_"+(b-1))});if(-1<d.indexOf(p,a)){var b=l.getValue(s,b),c=new Date(b);m[a]=D(c,b)?c.getTime():null}else if(-1<d.indexOf(r,a)){c=K.parse(l.getValue(s,b));if((a==h||a==n)&&(isNaN(c)||181<Math.abs(c)))c=parseFloat(l.getValue(s,b));isNaN(c)?m[a]=null:m[a]=c}else m[a]=l.getValue(s,b)}});m[v]=
g;g++;var t=m[h],x=m[n];null==x||null==t||(isNaN(t)||isNaN(x))||e.featureSet.features.push({geometry:{x:x,y:t,spatialReference:{wkid:4326}},attributes:m})}e.layerDefinition.name="csv";c&&c(e)}},onError:function(a){c&&c(null,a)}});return!0}function u(a,b,c,f,e,l){0===a.length&&e(null);var w=A.getGeometryType(b),k=[];d.forEach(a,function(a){a=new w(a);a.spatialReference=c;k.push(a)},this);b=[102113,102100,3857];c.wkid&&4326===c.wkid&&f.wkid&&-1<d.indexOf(b,f.wkid)?(d.forEach(k,function(a){a.xmin?(a.xmin=
Math.max(a.xmin,-180),a.xmax=Math.min(a.xmax,180),a.ymin=Math.max(a.ymin,-89.99),a.ymax=Math.min(a.ymax,89.99)):a.rings?d.forEach(a.rings,function(a){d.forEach(a,function(a){a[0]=Math.min(Math.max(a[0],-180),180);a[1]=Math.min(Math.max(a[1],-89.99),89.99)},this)},this):a.paths?d.forEach(a.paths,function(a){d.forEach(a,function(a){a[0]=Math.min(Math.max(a[0],-180),180);a[1]=Math.min(Math.max(a[1],-89.99),89.99)},this)},this):a.x&&(a.x=Math.min(Math.max(a.x,-180),180),a.y=Math.min(Math.max(a.y,-89.99),
89.99))},this),a=[],d.forEach(k,function(b){b=B.geographicToWebMercator(b);102100!==f.wkid&&(b.spatialReference=f);a.push(b.toJson())},this),e(a)):null!==c.wkid&&-1<d.indexOf(b,c.wkid)&&null!==f.wkid&&4326===f.wkid?(a=[],d.forEach(k,function(b){a.push(B.webMercatorToGeographic(b).toJson())},this),e(a)):(b=function(b,c){b&&b.length===a.length?(a=[],d.forEach(b,function(b){b&&(b.rings&&0<b.rings.length&&0<b.rings[0].length&&0<b.rings[0][0].length&&!isNaN(b.rings[0][0][0])&&!isNaN(b.rings[0][0][1])||
b.paths&&0<b.paths.length&&0<b.paths[0].length&&0<b.paths[0][0].length&&!isNaN(b.paths[0][0][0])&&!isNaN(b.paths[0][0][1])||b.xmin&&!isNaN(b.xmin)&&b.ymin&&!isNaN(b.ymin)||b.x&&!isNaN(b.x)&&b.y&&!isNaN(b.y))?a.push(b.toJson()):a.push(null)},this),e(a)):l(b,c)},z.defaults.geometryService?z.defaults.geometryService.project(k,f,h.hitch(this,b),l):e(null))}function H(a,b){var c=[102113,102100,3857];return a&&b&&a.wkid===b.wkid&&a.wkt===b.wkt||a&&b&&a.wkid&&b.wkid&&-1<d.indexOf(c,a.wkid)&&-1<d.indexOf(c,
b.wkid)?!0:!1}function I(a,b,c,f){if(a.featureSet&&0!==a.featureSet.features.length)if(H(c,b))f(a);else{var e=function(b){var c=[];d.forEach(a.featureSet.features,function(a,e){b[e]&&(a.geometry=b[e],c.push(a))},this);f(a)},l=function(b,c){f(a)},w=function(f,d){u(k,a.featureSet.geometryType,b,c,h.hitch(this,e),h.hitch(this,l))};if(a.featureSet.features&&0<a.featureSet.features.length){var k=[];d.forEach(a.featureSet.features,function(b){if(b.geometry.toJson)k.push(b.geometry);else{var c=A.getGeometryType(a.featureSet.geometryType);
k.push(new c(b.geometry))}});b.toJson||(b=new p(b));c.toJson||(c=new p(c));u(k,a.featureSet.geometryType,b,c,h.hitch(this,e),h.hitch(this,w))}else f(a)}}var F="lat latitude y ycenter latitude83 latdecdeg POINT-Y".split(" "),G="lon lng long longitude x xcenter longitude83 longdecdeg POINT-X".split(" ");return{latFieldStrings:F,longFieldStrings:G,buildCSVFeatureCollection:function(a){var b=new y,c=function(a,c){c?b.errback(c):b.callback(a)},f={url:a.url,handleAs:"text",load:function(b){E(b,a,h.hitch(this,
c))},error:function(a){b.errback(a)}};-1<a.url.indexOf("arcgis.com")&&-1<a.url.indexOf("/content/items")&&-1<a.url.indexOf("/data")&&(f.headers={"Content-Type":""});M(f,{usePost:!1});return b},projectFeatureCollection:function(a,b,c){var f=new y;c||(c=new p({wkid:4326}));I(a,c,b,h.hitch(this,function(a){f.callback(a)}));return f},generateDefaultPopupInfo:function(a){var b={esriFieldTypeDouble:1,esriFieldTypeSingle:1},c={esriFieldTypeInteger:1,esriFieldTypeSmallInteger:1},f={esriFieldTypeDate:1},e=
null;a=d.map(a.layerDefinition.fields,h.hitch(this,function(a){"NAME"===a.name.toUpperCase()&&(e=a.name);var d="esriFieldTypeOID"!==a.type&&"esriFieldTypeGlobalID"!==a.type&&"esriFieldTypeGeometry"!==a.type,k=null;if(d){var g=a.name.toLowerCase();if(-1<",stretched value,fnode_,tnode_,lpoly_,rpoly_,poly_,subclass,subclass_,rings_ok,rings_nok,".indexOf(","+g+",")||-1<g.indexOf("area")||-1<g.indexOf("length")||-1<g.indexOf("shape")||-1<g.indexOf("perimeter")||-1<g.indexOf("objectid")||g.indexOf("_")===
g.length-1||g.indexOf("_i")===g.length-2&&1<g.length)d=!1;a.type in c?k={places:0,digitSeparator:!0}:a.type in b?k={places:2,digitSeparator:!0}:a.type in f&&(k={dateFormat:"shortDateShortTime"})}return h.mixin({},{fieldName:a.name,label:a.alias,isEditable:!0,tooltip:"",visible:d,format:k,stringFieldOption:"textbox"})}));return{title:e?"{"+e+"}":"",fieldInfos:a,description:null,showAttachments:!1,mediaInfos:[]}},_getSeparator:C,_isValidDate:D,_processCsvData:E,_projectGeometries:u,_sameSpatialReference:H,
_projectFeatureSet:I}});
//@ sourceMappingURL=csv.js.map