//>>built
define("dojo-bootstrap/Modal","./Support dojo/_base/declare dojo/query dojo/_base/lang dojo/_base/window dojo/on dojo/dom-class dojo/dom-construct dojo/dom-attr dojo/dom-style dojo/request dojo/NodeList-dom dojo/NodeList-traverse dojo/NodeList-manipulate dojo/domReady!".split(" "),function(d,u,g,f,h,e,c,l,k,n,v){function w(a){var b=k.get(a,"data-target");b||(b=d.hrefValue(a));return!b?"":b}function x(){var a=this,b=setTimeout(function(){a.hideEvent&&a.hideEvent.remove();m.call(a)},500);a.hideEvent=
d.trans?e.once(a.domNode,d.trans.end,function(){clearTimeout(b);m.call(a)}):null}function m(){n.set(this.domNode,"display","none");e.emit(this.domNode,"hidden.bs.modal",{bubbles:!1,cancelable:!1});p.call(this)}function p(a){var b=c.contains(this.domNode,"fade")?"fade":"";if(this.isShown&&this.options.backdrop){var q=d.trans&&b;this.backdropNode=l.place('\x3cdiv class\x3d"modal-backdrop '+b+'" /\x3e',h.body());e(this.backdropNode,"click","static"!==this.options.backdrop?f.hitch(this.domNode,"focus"):
f.hitch(this,"hide"));q&&this.backdropNode.offsetWidth;c.add(this.backdropNode,"in");if(q)e.once(this.backdropNode,d.trans.end,a);else a()}else if(!this.isShown&&this.backdropNode)if(c.remove(this.backdropNode,"in"),d.trans&&c.contains(this.domNode,"fade"))e.once(this.backdropNode,d.trans.end,f.hitch(this,r));else r.call(this);else a&&a()}function r(){l.destroy(this.backdropNode);this.backdropNode=null}function s(){var a=this;a.isShown&&a.options.keyboard?a.keyupEvent=e(h.body(),"keyup",function(b){27===
b.which&&a.hide()}):a.isShown||a.keyupEvent&&a.keyupEvent.remove()}function y(){var a=this;a.focusInEvent=e(document,e.selector(".modal","focusin"),function(b){a.domNode!==this&&!g(this,a.domNode).length&&a.domNode.focus()})}var t=u([],{defaultOptions:{backdrop:!0,keyboard:!0,show:!0},constructor:function(a,b){this.options=f.mixin(f.clone(this.defaultOptions),b||{});var d=this.domNode=a;e(this.domNode,e.selector("[data-dismiss\x3dmodal]","click"),f.hitch(this,this.hide));this.options.remote&&v(this.options.remote).then(function(a){g(".modal-body",
d).html(a)})},toggle:function(){return this[!this.isShown?"show":"hide"]()},show:function(a){var b=this;e.emit(this.domNode,"show.bs.modal",{bubbles:!1,cancelable:!1});if(!this.isShown||!a.defaultPrevented)this.isShown=!0,s.call(this),p.call(this,function(){var a=d.trans&&c.contains(b.domNode,"fade");g(b.domNode).parent().length||l.place(b.domNode,h.body());n.set(b.domNode,"display","block");a&&(b._offsetWidth=b.domNode.offsetWidth);c.add(b.domNode,"in");k.set(b.domNode,"aria-hidden",!1);y.call(b);
if(a)e.once(b.domNode,d.trans.end,function(){b.domNode.focus();e.emit(b.domNode,"shown.bs.modal",{bubbles:!1,cancelable:!1})});else b.domNode.focus(),e.emit(b.domNode,"shown.bs.modal",{bubbles:!1,cancelable:!1})})},hide:function(a){e.emit(this.domNode,"hide.bs.modal",{bubbles:!1,cancelable:!1});a&&a.preventDefault();if(this.isShown||!a.defaultPrevented)this.isShown=!1,s.call(this),this.focusInEvent&&this.focusInEvent.remove(),c.remove(this.domNode,"in"),k.set(this.domNode,"aria-hidden",!0),d.trans&&
c.contains(this.domNode,"fade")?x.call(this):m.call(this)}});f.extend(g.NodeList,{modal:function(a){return this.forEach(function(b){var e=f.mixin({},f.mixin(d.getData(b),f.isObject(a)&&a)),c=d.getData(b,"modal");c||d.setData(b,"modal",c=new t(b,e));f.isString(a)?c[a].call(c):c&&c.options.show&&c.show()})}});e(h.body(),e.selector("[data-toggle\x3dmodal]","click"),function(a){var b=g(w(this));if(void 0!==b[0]){var c=k.get(this,"href"),c=d.getData(b,"modal")?"toggle":f.mixin({remote:!/#/.test(c)&&c},
f.mixin(d.getData(b),d.getData(this)));"toggle"===c&&f.mixin(d.getData(b,"modal").options,d.getData(this));b.modal(c);e.once(b[0],"hide",function(){b[0].focus()})}a&&a.preventDefault()});return t});
//@ sourceMappingURL=Modal.js.map