//>>built
define("dojo-bootstrap/Tooltip","./Support dojo/_base/declare dojo/query dojo/_base/lang dojo/_base/array dojo/_base/window dojo/on dojo/mouse dojo/dom-class dojo/dom-attr dojo/dom-style dojo/dom-geometry dojo/dom-construct dojo/html dojo/NodeList-dom dojo/NodeList-manipulate dojo/NodeList-traverse dojo/domReady!".split(" "),function(l,w,m,f,x,z,g,s,n,p,q,y,t,A){var u=w("Tooltip",null,{defaultOptions:{animation:!0,placement:"top",selector:!1,template:'\x3cdiv class\x3d"tooltip"\x3e\x3cdiv class\x3d"tooltip-arrow"\x3e\x3c/div\x3e\x3cdiv class\x3d"tooltip-inner"\x3e\x3c/div\x3e\x3c/div\x3e',
trigger:"hover focus",title:"",delay:0,html:!1,container:!1},constructor:function(b,a){this.init("tooltip",b,a)},init:function(b,a,c){var d=this,e,h=function(){d.hide(!1)};this.domNode=a;this.type=b;this.options=this.getOptions(c);this.enabled=!0;a=this.options.trigger.split(" ");for(c=a.length;c--;)e=a[c],"click"===e?(m(this.domNode).parents(".modal").on("hide",h),this.eventActivate=this.options.selector?g(this.domNode,g.selector(this.options.selector,"click"),f.hitch(this,"toggle")):g(this.domNode,
"click",f.hitch(this,"toggle"))):"manual"!==e&&(b="hover"===e?s.enter:"focusin",e="hover"===e?s.leave:"focusout",this.options.selector&&(b=g.selector(this.options.selector,b),e=g.selector(this.options.selector,e)),this.eventActivate=g(this.domNode,b,f.hitch(d,"enter")),this.eventDeactivate=g(this.domNode,e,f.hitch(d,"leave")));this.options.selector?this._options=f.mixin({},f.mixin(f.clone(this.options),{trigger:"manual",selector:""})):this.fixTitle()},getOptions:function(b){b=f.mixin({},f.mixin(f.clone(this.defaultOptions),
f.mixin(b,l.getData(this.domNode))));b.delay&&"number"===typeof b.delay&&(b.delay={show:b.delay,hide:b.delay});return b},getDelegateOptions:function(){var b={},a=this.defaultOptions;this._options&&x.forEach(this._options,function(c,d){a[c]!==d&&(b[c]=d)});return b},enter:function(b){var a=l.getData(b.target,"bs."+this.type);a||(m(b.target)[this.type](this.getDelegateOptions()),a=l.getData(b.target,"bs."+this.type));a&&a.timeout&&clearTimeout(a.timeout);if(a){if(!a.options.delay||!a.options.delay.show)return a.show();
a.hoverState="in";a.timeout=setTimeout(function(){"in"===a.hoverState&&a.show()},a.options.delay.show)}return a},leave:function(b){var a=l.getData(b.target,"bs."+this.type);a||(m(b.target)[this.type](this.getDelegateOptions()),a=l.getData(b.target,"bs."+this.type));a&&a.timeout&&clearTimeout(this.timeout);if(a){if(!a.options.delay||!a.options.delay.hide)return a.hide();a.hoverState="out";a.timeout=setTimeout(function(){"out"===a.hoverState&&a.hide()},a.options.delay.hide)}return this},show:function(b){var a=
this,c,d,e,h,k;b=b||!0;if(this.hasContent()&&this.enabled){g.emit(this.domNode,"show.bs."+this.type,{bubbles:!1,cancelable:!1});c=this.tip();this.setContent();!0===this.options.animation&&n.add(c,"fade");k="function"===typeof this.options.placement?this.options.placement.call(this,c,this.domNode):this.options.placement;d=/\s?auto?\s?/i;var f=d.test(k);f&&(k=k.replace(d,"")||"top");m(c).remove().addClass(k);q.set(c,{top:0,left:0,display:"block"});l.setData(c,"bs."+this.type,this);this.options.container?
t.place(c,this.options.container):t.place(c,this.domNode,"after");d=this.getPosition();e=c.offsetWidth;h=c.offsetHeight;if(f){var r=y.position(this.domNode.parentNode,!0),f=document.documentElement.scrollTop||document.body.scrollTop,p=k,s="body"===this.options.container?window.innerWidth:r.w,u="body"===this.options.container?window.innerHeight:r.h,r="body"===this.options.container?0:r.x;k="bottom"===k&&d.y+d.height+h-f>u?"top":"top"===k&&0>d.y-f-h?"bottom":"right"===k&&d.x+d.w+e>s?"left":"left"===
k&&d.x-e<r?"right":k;n.remove(c,p);n.add(c,k)}d=this.getCalculatedOffset(k,d,e,h);this.applyPlacement(d,k);this.hoverState=null;var v=function(){g.emit(a.domNode,"shown.bs."+a.type,{bubbles:!1,cancelable:!1})};if(l.trans&&n.contains(c,"fade")&&b)g.once(c,l.trans.end,function(){v()});else v()}},hide:function(b){function a(){var a=setTimeout(function(){d.hideEvent.remove()},500);d.hideEvent=g.once(e,l.trans.end,function(){clearTimeout(a);c()})}function c(){t.destroy(e);d.tipNode=null;g.emit(d.domNode,
"hidden.bs."+d.type,{bubbles:!1,cancelable:!1})}var d=this,e=this.tip();b=b||!0;g.emit(this.domNode,"hide.bs."+this.type,{bubbles:!1,cancelable:!1});n.remove(e,"in");l.trans&&n.contains(e,"fade")&&b?a():c();return this},getCalculatedOffset:function(b,a,c,d){return"bottom"===b?{y:a.y+a.h,x:a.x+a.w/2-c/2}:"top"===b?{y:a.y-d,x:a.x+a.w/2-c/2}:"left"===b?{y:a.y+a.h/2-d/2,x:a.x-c}:{y:a.y+a.h/2-d/2,x:a.x+a.w}},applyPlacement:function(b,a){var c,d,e,h=this.tip(),k=h.offsetWidth,g=h.offsetHeight;d=parseInt(q.get(h,
"margin-top"),10);e=parseInt(q.get(h,"margin-left"),10);isNaN(d)&&(d=0);isNaN(e)&&(e=0);b.y+=d;b.x+=e;l.setOffset(h,f.mixin({using:function(a){q.set(h,{top:Math.round(a.y)+"px",left:Math.round(a.x)+"px"})}},b),0);n.add(h,"in");d=h.offsetWidth;e=h.offsetHeight;"top"===a&&e!==g&&(c=!0,b.y=b.y+g-e);/bottom|top/.test(a)?(g=0,0>b.x&&(g=-2*b.x,b.x=0,m(h).offset(b),d=h.offsetWidth),this.replaceArrow(g-k+d,d,"left")):this.replaceArrow(e-g,e,"top");c&&m(h).offset(b)},replaceArrow:function(b,a,c){q.set(this.arrow(),
c,b?50*(1-b/a)+"%":"")},setContent:function(){var b=this.tip(),a=this.getTitle();m(".tooltip-inner",b)[this.options.html?"html":"text"](a);n.remove(b,"fade in top bottom left right")},hasContent:function(){return this.getTitle()},fixTitle:function(){if(p.get(this.domNode,"title")||"string"!==typeof p.get(this.domNode,"data-original-title"))p.set(this.domNode,"data-original-title",p.get(this.domNode,"title")||""),p.remove(this.domNode,"title")},getTitle:function(){return p.get(this.domNode,"data-original-title")||
("function"===typeof this.options.title?this.options.title.call(this.domNode):this.options.title)},getPosition:function(){var b=this.domNode,a={};if("function"===typeof b.getBoundingClientRect){var c=b.getBoundingClientRect();a.w=c.width;a.h=c.height;a.y=c.top;a.x=c.left;a.b=c.bottom;a.r=c.right}else a.w=b.offsetWidth,a.h=b.offsetHeight;return f.mixin({},a,m(b).offset())},tip:function(){return this.tipNode=this.tipNode?this.tipNode:t.toDom(this.options.template)},arrow:function(){return this.arrowNode=
this.arrowNode?this.arrowNode:m(".tooltip-arrow",this.tip())[0]},validate:function(){this.domNode.parentNode||(this.hide(!1),this.options=this.domNode=null)},enable:function(){this.enabled=!0},disable:function(){this.enabled=!1},toggleEnabled:function(){this.enabled=!this.enabled},toggle:function(){this[n.contains(this.tip(),"in")?"hide":"show"]()},destroy:function(){this.hide();this.eventActivate&&this.eventActivate.remove();this.eventDeactivate&&this.eventDeactivate.remove();l.removeData(this.domNode,
"tooltip")}});f.extend(m.NodeList,{tooltip:function(b){var a=f.isObject(b)?b:{};return this.forEach(function(c){var d=l.getData(c,"bs.tooltip");d||l.setData(c,"bs.tooltip",d=new u(c,a));f.isString(b)&&d[b].call(d)})}});m("[data-toggle\x3dtooltip]").tooltip();return u});
//@ sourceMappingURL=Tooltip.js.map