//>>built
define("dojo-bootstrap/Typeahead","dojo/_base/declare dojo/query dojo/_base/lang dojo/_base/window dojo/on dojo/dom-class dojo/dom-attr dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/_base/array ./Support dojo/NodeList-dom dojo/NodeList-traverse dojo/domReady!".split(" "),function(n,d,c,s,b,p,g,h,q,l,k,f){var m=n([],{defaultOptions:{source:[],items:8,menu:'\x3cul class\x3d"typeahead dropdown-menu"\x3e\x3c/ul\x3e',item:'\x3cli\x3e\x3ca href\x3d"#"\x3e\x3c/a\x3e\x3c/li\x3e',minLength:1,autocomplete:!1},
constructor:function(a,r){this.options=c.mixin(c.clone(this.defaultOptions),r||{});this.domNode=a;!1===this.options.autocomplete&&g.set(a,"autocomplete","off");this.matcher=this.options.matcher||this.matcher;this.sorter=this.options.sorter||this.sorter;this.highlighter=this.options.highlighter||this.highlighter;this.updater=this.options.updater||this.updater;this.menuNode=h.toDom(this.options.menu);this.source=this.options.source;this.shown=!1;this.listen()},select:function(){var a=d(".active",this.menuNode)[0];
this.domNode.value=this.updater(g.get(a,"data-value"));b.emit(this.domNode,"change",{bubbles:!0,cancelable:!0});return this.hide()},updater:function(a){return a},show:function(){var a=q.position(this.domNode,!0);h.place(this.menuNode,document.body);l.set(this.menuNode,{top:a.y+this.domNode.offsetHeight+"px",left:a.x+"px",display:"block"});this.shown=!0;return this},hide:function(){l.set(this.menuNode,"display","none");this.shown=!1;return this},lookup:function(){var a;this.query=this.domNode.value;
return!this.query||this.query.length<this.options.minLength?this.shown?this.hide():this:(a="function"===typeof this.source?this.source(this.query,c.hitch(this,"process")):this.source)?this.process(a):this},process:function(a){a=k.filter(a,function(a){return this.matcher(a)},this);a=this.sorter(a);if(!a.length)return this.shown?this.hide():this;this.render(a.slice(0,this.options.items)).show()},matcher:function(a){return a.toString().toLowerCase().indexOf(this.query.toLowerCase())+1},sorter:function(a){for(var c=
[],d=[],e=[],b;b=a.shift();)b.toString().toLowerCase().indexOf(this.query.toString().toLowerCase())?0<=b.toString().indexOf(this.query)?d.push(b):e.push(b):c.push(b);return c.concat(d,e)},highlighter:function(a){var b=this.query.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$\x26");return a.toString().replace(RegExp("("+b+")","ig"),function(a,b){return"\x3cstrong\x3e"+b+"\x3c/strong\x3e"})},render:function(a){a=k.map(a,function(a,b){var c=h.toDom(this.options.item);g.set(c,"data-value",a);d("a",c)[0].innerHTML=
this.highlighter(a);0===b&&p.add(c,"active");return c.outerHTML},this);this.menuNode.innerHTML=a.join("");return this},next:function(){var a=d(".active",this.menuNode);a.removeClass("active");a=a.next();a.length||(a=d("li",this.menuNode).first());a.addClass("active")},prev:function(){var a=d(".active",this.menuNode);a.removeClass("active");a=a.prev();a.length||(a=d("li",this.menuNode).last());a.addClass("active")},listen:function(){b(this.domNode,"blur",c.hitch(this,"blur"));b(this.domNode,"keypress",
c.hitch(this,this.keypress));b(this.domNode,"keyup",c.hitch(this,this.keyup));f.eventSupported(this.domNode,"keydown")&&b(this.domNode,"keydown",c.hitch(this,"keydown"));b(this.menuNode,"click",c.hitch(this,"click"));b(this.menuNode,b.selector("li","mouseover"),c.hitch(this,"mouseenter"))},move:function(a){if(this.shown){switch(a.charCode||a.keyCode){case 9:case 13:case 27:a.preventDefault();break;case 38:a.preventDefault();this.prev();break;case 40:a.preventDefault(),this.next()}a.stopPropagation()}},
keyup:function(a){switch(a.charCode||a.keyCode){case 40:case 38:case 16:case 17:case 18:break;case 9:case 13:if(!this.shown)return;this.select();break;case 27:if(!this.shown)return;this.hide();break;default:this.lookup()}a.stopPropagation();a.preventDefault()},keydown:function(a){this.suppressKeyPressRepeat=0<=k.indexOf([40,38,9,13,27],a.charCode||a.keyCode);this.move(a)},keypress:function(a){this.suppressKeyPressRepeat||this.move(a)},blur:function(){var a=this;setTimeout(function(){a.hide()},150)},
click:function(a){a.stopPropagation();a.preventDefault();this.select()},mouseenter:function(a){a=d(a.target).closest("li");d(".active",this.menuNode).removeClass("active");a.addClass("active")}});c.extend(d.NodeList,{typeahead:function(a){var b=c.isObject(a)?a:{};return this.forEach(function(d){var e=f.getData(d,"typeahead");e||f.setData(d,"typeahead",e=new m(d,b));c.isString(a)&&e[a].call(e)})}});b(document,b.selector('[data-provide\x3d"typeahead"]',"focusin"),function(a){f.getData(this,"typeahead")||
(a.preventDefault(),d(this).typeahead(f.getData(this)))});return m});
//@ sourceMappingURL=Typeahead.js.map