//>>built
define("dgrid/extensions/ColumnResizer","dojo/_base/declare dojo/on dojo/query dojo/_base/lang dojo/dom dojo/dom-geometry dojo/has ../util/misc put-selector/put dojo/_base/html xstyle/css!../css/extensions/ColumnResizer.css".split(" "),function(A,m,p,w,x,B,v,u,e){function y(a){for(var b=a.length,c=b,g=a[0].length,h=Array(b);b--;)h[b]=Array(g);for(var l={},b=0;b<c;b++)for(var f=h[b],C=a[b],n=0,d=0;n<g;n++){var k=C[d],s;if("undefined"==typeof f[n]){f[n]=k.id;if(k.rowSpan&&1<k.rowSpan){s=h;for(var e=
k.rowSpan,p=b,q=n,r=k.id,t=1;t<e;t++)s[p+t][q]=r}if(0<b&&k.colSpan&&1<k.colSpan)for(s=1;s<k.colSpan;s++)if(f[++n]=k.id,k.rowSpan&&1<k.rowSpan)for(var e=h,p=k.rowSpan,q=b,r=n,t=k.id,m=1;m<p;m++)e[q+m][r]=t;l[k.id]=a[0][n].id;d++}}return l}function q(a,b,c,g,h){if(!(0>=c)){var l=a.columns[b],f;if(l&&(f={grid:a,columnId:b,width:c,bubbles:!0,cancelable:!0},g&&(f.parentType=g),!a._resizedColumns||m.emit(a.headerNode,"dgrid-columnresize",f)))return"auto"===c?delete l.width:(l.width=c,c+="px"),(g=a._columnSizes[b])?
g.set("width",c):g=u.addCssRule("#"+u.escapeCssIdentifier(a.domNode.id)+" .dgrid-column-"+b,"width: "+c+";"),a._columnSizes[b]=g,!1!==h&&a.resize(),!0}}var d,z=0,r={create:function(){d=e("div.dgrid-column-resizer")},destroy:function(){e(d,"!");d=null},show:function(a){a=B.position(a.domNode,!0);d.style.top=a.y+"px";d.style.height=a.h+"px";e(document.body,d)},move:function(a){d.style.left=a+"px"},hide:function(){d.parentNode.removeChild(d)}};return A(null,{resizeNode:null,minWidth:40,adjustLastColumn:!0,
_resizedColumns:!1,buildRendering:function(){this.inherited(arguments);z++||r.create()},destroy:function(){this.inherited(arguments);for(var a in this._columnSizes)this._columnSizes[a].remove();--z||r.destroy()},resizeColumnWidth:function(a,b){return q(this,a,b)},configStructure:function(){var a=this._oldColumnSizes=w.mixin({},this._columnSizes),b;this._resizedColumns=!1;this._columnSizes={};this.inherited(arguments);for(b in a)b in this._columnSizes||a[b].remove();delete this._oldColumnSizes},_configColumn:function(a){this.inherited(arguments);
var b=a.id,c;"width"in a&&((c=this._oldColumnSizes[b])?c.set("width",a.width+"px"):c=u.addCssRule("#"+this.domNode.id+" .dgrid-column-"+b,"width: "+a.width+"px;"),this._columnSizes[b]=c)},renderHeader:function(){this.inherited(arguments);var a=this,b;if(this.columnSets&&this.columnSets.length)for(var c=this.columnSets.length;c--;)b=w.mixin(b||{},y(this.columnSets[c]));else this.subRows&&1<this.subRows.length&&(b=y(this.subRows));for(var c=p(".dgrid-cell",a.headerNode),g=c.length;g--;){var h=c[g],
l=h.columnId,f=a.columns[l],d=h.childNodes;if(f&&!1!==f.resizable){f=e("div.dgrid-resize-header-container");for(h.contents=f;0<d.length;)e(f,d[0]);e(h,f,"div.dgrid-resize-handle.resizeNode-"+l).columnId=b&&b[l]||l}}a.mouseMoveListen||(m(a.headerNode,".dgrid-resize-handle:mousedown"+(v("touch")?",.dgrid-resize-handle:touchstart":""),function(b){a._resizeMouseDown(b,this);a.mouseMoveListen.resume();a.mouseUpListen.resume()}),a._listeners.push(a.mouseMoveListen=m.pausable(document,"mousemove"+(v("touch")?
",touchmove":""),u.throttleDelayed(function(b){a._updateResizerPosition(b)}))),a._listeners.push(a.mouseUpListen=m.pausable(document,"mouseup"+(v("touch")?",touchend":""),function(b){a._resizeMouseUp(b);a.mouseMoveListen.pause();a.mouseUpListen.pause()})),a.mouseMoveListen.pause(),a.mouseUpListen.pause())},_resizeMouseDown:function(a,b){a.preventDefault();x.setSelectable(this.domNode,!1);this._startX=this._getResizeMouseLocation(a);this._targetCell=p(".dgrid-column-"+b.columnId,this.headerNode)[0];
this._updateResizerPosition(a);r.show(this)},_resizeMouseUp:function(a){var b=this._columnSizes,c,g,h;this.adjustLastColumn&&(h=this.headerNode.clientWidth-1);this._resizedColumns||(c=p(".dgrid-cell",this.headerNode),this.columnSets&&this.columnSets.length?c=c.filter(function(a){return"0"==a.columnId.split("-")[0]&&!(a.columnId in b)}):this.subRows&&1<this.subRows.length&&(c=c.filter(function(a){return"0"==a.columnId.charAt(0)&&!(a.columnId in b)})),g=c.map(function(a){return a.offsetWidth}),c.forEach(function(a,
b){q(this,a.columnId,g[b],null,!1)},this),this._resizedColumns=!0);x.setSelectable(this.domNode,!0);c=this._targetCell;var d=this._getResizeMouseLocation(a)-this._startX,f=c.offsetWidth+d,e=this._getResizedColumnWidths(),n=e.totalWidth,e=e.lastColId,m=p(".dgrid-column-"+e,this.headerNode)[0].offsetWidth;f<this.minWidth&&(f=this.minWidth);q(this,c.columnId,f,a.type)&&c.columnId!=e&&this.adjustLastColumn&&(n+d<h?q(this,e,"auto",a.type):m-d<=this.minWidth&&q(this,e,this.minWidth,a.type));r.hide();delete this._startX;
delete this._targetCell},_updateResizerPosition:function(a){if(this._targetCell){a=this._getResizeMouseLocation(a);var b=this._targetCell.offsetWidth,c=a;b+(a-this._startX)<this.minWidth&&(c=this._startX-(b-this.minWidth));r.move(c)}},_getResizeMouseLocation:function(a){var b=0;a.pageX?b=a.pageX:a.clientX&&(b=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft);return b},_getResizedColumnWidths:function(){var a=0,b=p(".dgrid-cell",this.headerNode);this.columnSets&&this.columnSets.length?
b=b.filter(function(a){return"0"==a.columnId.split("-")[1]}):this.subRows&&1<this.subRows.length&&(b=b.filter(function(a){return"0"==a.columnId.charAt(0)}));var c=b.length;if(!c)return{};for(var d=b[c-1].columnId;c--;)a+=b[c].offsetWidth;return{totalWidth:a,lastColId:d}}})});
//@ sourceMappingURL=ColumnResizer.js.map