//>>built
define("dgrid/extensions/Pagination","../_StoreMixin dojo/_base/declare dojo/_base/array dojo/_base/lang dojo/_base/Deferred dojo/on dojo/query dojo/string dojo/has put-selector/put dojo/i18n!./nls/pagination dojo/_base/sniff xstyle/css!../css/extensions/Pagination.css".split(" "),function(x,y,z,t,r,l,u,v,s,d,A){function B(a){a.noDataNode?(d(a.noDataNode,"!"),delete a.noDataNode):a.cleanup();a.contentNode.innerHTML=""}function w(a){if(a.loadingNode)d(a.loadingNode,"!"),delete a.loadingNode;else if(a._oldPageNodes){for(var c in a._oldPageNodes)a.removeRow(a._oldPageNodes[c]);
delete a._oldPageNodes;a._oldPageObserver&&(a._oldPageObserver.cancel(),a._numObservers--,delete a._oldPageObserver)}delete a._isLoading}return y(x,{rowsPerPage:10,pagingTextBox:!1,previousNextArrows:!0,firstLastArrows:!1,pagingLinks:2,pageSizeOptions:null,showLoadingMessage:!0,i18nPagination:A,showFooter:!0,_currentPage:1,_total:0,buildRendering:function(){this.inherited(arguments);var a=this,c=this.paginationNode=d(this.footerNode,"div.dgrid-pagination"),b=this.paginationStatusNode=d(c,"div.dgrid-status"),
g=this.i18nPagination;b.tabIndex=0;this._updatePaginationSizeSelect();this._updateRowsPerPageOption();b.innerHTML=v.substitute(g.status,{start:1,end:1,total:0});c=this.paginationNavigationNode=d(c,"div.dgrid-navigation");this.firstLastArrows&&(b=this.paginationFirstNode=d(c,"span.dgrid-first.dgrid-page-link","\u00ab"),b.setAttribute("aria-label",g.gotoFirst),b.tabIndex=0);this.previousNextArrows&&(b=this.paginationPreviousNode=d(c,"span.dgrid-previous.dgrid-page-link","\u2039"),b.setAttribute("aria-label",
g.gotoPrev),b.tabIndex=0);this.paginationLinksNode=d(c,"span.dgrid-pagination-links");this.previousNextArrows&&(b=this.paginationNextNode=d(c,"span.dgrid-next.dgrid-page-link","\u203a"),b.setAttribute("aria-label",g.gotoNext),b.tabIndex=0);this.firstLastArrows&&(b=this.paginationLastNode=d(c,"span.dgrid-last.dgrid-page-link","\u00bb"),b.setAttribute("aria-label",g.gotoLast),b.tabIndex=0);this._listeners.push(l(c,".dgrid-page-link:click,.dgrid-page-link:keydown",function(b){if(!("keydown"===b.type&&
13!==b.keyCode)){b=this.className;var c,d;a._isLoading||-1<b.indexOf("dgrid-page-disabled")||(c=a._currentPage,d=Math.ceil(a._total/a.rowsPerPage),this===a.paginationPreviousNode?a.gotoPage(c-1):this===a.paginationNextNode?a.gotoPage(c+1):this===a.paginationFirstNode?a.gotoPage(1):this===a.paginationLastNode?a.gotoPage(d):"dgrid-page-link"===b&&a.gotoPage(+this.innerHTML,!0))}}))},destroy:function(){this.inherited(arguments);this._pagingTextBoxHandle&&this._pagingTextBoxHandle.remove()},_updatePaginationSizeSelect:function(){var a=
this.pageSizeOptions,c=this.paginationSizeSelect,b;if(a&&a.length){c||(c=this.paginationSizeSelect=d(this.paginationNode,"select.dgrid-page-size"),b=this._paginationSizeChangeHandle=l(c,"change",t.hitch(this,function(){this.set("rowsPerPage",+this.paginationSizeSelect.value)})),this._listeners.push(b));for(i=c.options.length=0;i<a.length;i++)d(c,"option",a[i],{value:a[i],selected:this.rowsPerPage===a[i]});this._updateRowsPerPageOption()}else if((!a||!a.length)&&c)d(c,"!"),this.paginationSizeSelect=
null,this._paginationSizeChangeHandle.remove()},_setPageSizeOptions:function(a){this.pageSizeOptions=a&&a.sort(function(a,b){return a-b});this._updatePaginationSizeSelect()},_updateRowsPerPageOption:function(){var a=this.rowsPerPage,c=this.pageSizeOptions,b=this.paginationSizeSelect;b&&(0>z.indexOf(c,a)?this._setPageSizeOptions(c.concat([a])):b.value=""+a)},_setRowsPerPage:function(a){this.rowsPerPage=a;this._updateRowsPerPageOption();this.gotoPage(1)},_updateNavigation:function(a){function c(c,e){var n;
b.pagingTextBox&&c==h&&1<f?(n=d(k,"input.dgrid-page-input[type\x3dtext][value\x3d$]",h),n.setAttribute("aria-label",g.jumpPage),b._pagingTextBoxHandle=l(n,"change",function(){var a=+this.value;!isNaN(a)&&(0<a&&a<=f)&&b.gotoPage(+this.value,!0)})):(n=d(k,"span"+(c==h?".dgrid-page-disabled":"")+".dgrid-page-link",c+(e?" ":"")),n.setAttribute("aria-label",g.gotoPage),n.tabIndex=0);c==h&&a&&n.focus()}var b=this,g=this.i18nPagination,k=this.paginationLinksNode,h=this._currentPage,m=this.pagingLinks,e=
this.paginationNavigationNode,f=Math.ceil(this._total/this.rowsPerPage),p=this._pagingTextBoxHandle;p&&p.remove();k.innerHTML="";u(".dgrid-first, .dgrid-previous",e).forEach(function(a){d(a,(1==h?".":"!")+"dgrid-page-disabled")});u(".dgrid-last, .dgrid-next",e).forEach(function(a){d(a,(h>=f?".":"!")+"dgrid-page-disabled")});if(m&&0<f){c(1,!0);e=h-m;for(2<e?d(k,"span.dgrid-page-skip","..."):e=2;e<Math.min(h+m+1,f);e++)c(e,!0);h+m+1<f&&d(k,"span.dgrid-page-skip","...");1<f&&c(f)}else b.pagingTextBox&&
c(h)},refresh:function(){var a=this;this.inherited(arguments);if(this.store)return this.gotoPage(1).then(function(c){setTimeout(function(){l.emit(a.domNode,"dgrid-refresh-complete",{bubbles:!0,cancelable:!1,grid:a,results:c})},0);return c})},_onNotification:function(a){a.length!==this._rowsOnPage&&this.gotoPage(this._currentPage)},renderArray:function(a,c){var b=this,d=this.inherited(arguments);this._lastCollection=null;c||(this._topLevelRequest&&this._topLevelRequest!==a&&(this._topLevelRequest.cancel(),
delete this._topLevelRequest),"function"===typeof a.cancel&&(this._topLevelRequest=a),r.when(a,function(){b._topLevelRequest&&delete b._topLevelRequest}));return d},insertRow:function(){var a=this._oldPageNodes,c=this.inherited(arguments);a&&c===a[c.id]&&delete a[c.id];return c},gotoPage:function(a,c){var b=this,g=new r;this._trackError(function(){var k=b.rowsPerPage,h=(a-1)*k,m=t.mixin(b.get("queryOptions"),{start:h,count:k}),e,f=b.contentNode,p,q,l;if(b.showLoadingMessage)B(b),p=b.loadingNode=d(f,
"div.dgrid-loading"),p.innerHTML=b.loadingMessage;else{b._oldPageNodes=p={};f=f.children;q=0;for(l=f.length;q<l;q++)p[f[q].id]=f[q];b._oldPageObserver=b.observers.pop()}b._isLoading=!0;e=b.store.query(b.query,m);r.when(b.renderArray(e,null,m),function(f){w(b);b.scrollTo({y:0});r.when(e.total,function(e){e||(b.noDataNode&&(d(b.noDataNode,"!"),delete b.noDataNode),b.noDataNode=d(b.contentNode,"div.dgrid-no-data"),b.noDataNode.innerHTML=b.noDataMessage);b.paginationStatusNode.innerHTML=v.substitute(b.i18nPagination.status,
{start:Math.min(h+1,e),end:Math.min(e,h+k),total:e});b._total=e;b._currentPage=a;b._rowsOnPage=f.length;b._updateNavigation(c)});(7>s("ie")||s("ie")&&s("quirks"))&&b.resize();g.resolve(e)},function(a){w(b);g.reject(a)});return g.promise})||g.reject();return g.promise}})});
//@ sourceMappingURL=Pagination.js.map