//>>built
define("esri/renderers/Renderer","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has dojox/gfx/_base ../kernel ../Color".split(" "),function(s,h,k,t,p,u,m){return s(null,{declaredClass:"esri.renderer.Renderer",constructor:function(a){if(a&&!a.declaredClass){this.rotationInfo=a.rotationInfo;if(!this.rotationInfo){var b=a.rotationType,d=a.rotationExpression;if(b||d)this.rotationInfo={type:b,expression:d}}this.setRotationInfo(this.rotationInfo);if(b=a.proportionalSymbolInfo)b.minSize&&(b.minSize=
p.pt2px(b.minSize)),b.maxSize&&(b.maxSize=p.pt2px(b.maxSize));this.setProportionalSymbolInfo(b);var c=a.colorInfo;c&&(k.forEach(c.colors,function(a,b){h.isArray(a)&&(c.colors[b]=m.toDojoColor(a))}),k.forEach(c.stops,function(a,b){a.color&&h.isArray(a.color)&&(c.stops[b].color=m.toDojoColor(a.color))}));this.setColorInfo(c);this.setOpacityInfo(a.opacityInfo)}this.getSymbol=h.hitch(this,this.getSymbol)},getSymbol:function(a){},setRotationInfo:function(a){if((a=this.rotationInfo="string"===typeof a?
{field:a}:a)&&a.expression&&!a.field){var b=a.expression.match(this.rotationRE);b&&b[1]&&(a.field=b[1])}return this},rotationRE:/^\[([^\]]+)\]$/i,getRotationAngle:function(a){var b=this.rotationInfo,d="arithmetic"===b.type,b=b.field,c=a.attributes,f=0;b&&(h.isFunction(b)?f=b.apply(this,arguments):c&&(f=c[b]||0),f=(f+(d?-90:0))*(d?-1:1));return f},setProportionalSymbolInfo:function(a){this.proportionalSymbolInfo=a;return this},getSize:function(a,b){var d=a.attributes,c=this.proportionalSymbolInfo,
f=c&&c.field,e=0,g="number"===typeof a?a:null;if(f){var l=c.minSize,k=c.maxSize,n=c.minDataValue,m=c.maxDataValue,p=c.valueUnit||"unknown",q=c.valueRepresentation,c=c.normalizationField,r=d?parseFloat(d[c]):void 0,c=b&&b.shape;"number"!==typeof g&&(h.isFunction(f)?g=f.apply(this,arguments):d&&(g=d[f]||0));isNaN(r)||(g/=r);if(null!=l&&null!=k&&null!=n&&null!=m)e=g<=n?l:g>=m?k:l+(g-n)/(m-n)*(k-l);else if("unknown"===p)null!=l&&null!=n&&(l&&n?(g/=n,e="circle"===c?2*Math.sqrt(g*Math.pow(l/2,2)):"square"===
c||"diamond"===c||"image"===c?Math.sqrt(g*Math.pow(l,2)):g*l):e=g+(l||n),e=e<l?l:e,null!=k&&e>k&&(e=k));else{d=(b&&b.resolution?b.resolution:a.getLayer().getMap().getResolutionInMeters())*this._meterIn[p];if("area"===q)e=Math.sqrt(g/Math.PI)/d,e*=2;else if(e=g/d,"radius"===q||"distance"===q)e*=2;null!=l&&e<l&&(e=l);null!=k&&e>k&&(e=k)}}return isNaN(e)?0:e},setColorInfo:function(a){if(this.colorInfo=a)k.forEach(a.colors,function(b,d){h.isArray(b)&&(a.colors[d]=new m(b))}),k.forEach(a.stops,function(b,
d){b.color&&h.isArray(b.color)&&(a.stops[d].color=new m(b.color))});this._ipDataForColors=this._interpolateData(a);return this},getColor:function(a){return this._getColorComponent(a,this.colorInfo)},setOpacityInfo:function(a){this.opacityInfo=a;this._ipDataForOpac=this._interpolateData(a);return this},getOpacity:function(a){return this._getColorComponent(a,this.opacityInfo,!0)},_getColorComponent:function(a,b,d){var c=a.attributes,f=b&&b.field,e="number"===typeof a?a:null,g;f&&(g=b.normalizationField,
g=c?parseFloat(c[g]):void 0,"number"!==typeof e&&(h.isFunction(f)?e=f.apply(this,arguments):c&&(e=c[f]||0)),isNaN(g)||(e/=g),g=d?this._getOpacity(e):this._getColor(e));return g},_interpolateData:function(a){var b;if(a)if(a.colors||a.opacityValues){var d=(a.colors||a.opacityValues).length,c=a.minDataValue,f=(a.maxDataValue-c)/(d-1);b=[];for(a=0;a<d;a++)b[a]=c+a*f}else a.stops&&(b=k.map(a.stops,function(a){return a.value}));return b},_getOpacity:function(a){a=this._lookupData(a,this._ipDataForOpac);
var b=this.opacityInfo,d;if(a){var c=a[0];d=a[1];c===d?d=this._getOpacValue(b,c):(c=this._getOpacValue(b,c),b=this._getOpacValue(b,d),d=c+(b-c)*a[2])}return d},_getOpacValue:function(a,b){return a.opacityValues?a.opacityValues[b]:a.stops[b].opacity},_getColor:function(a){a=this._lookupData(a,this._ipDataForColors);var b=this.colorInfo,d;if(a){d=a[0];var c=a[1];d=d===c?this._getColorObj(b,d):m.blendColors(this._getColorObj(b,d),this._getColorObj(b,c),a[2])}return d},_getColorObj:function(a,b){return a.colors?
a.colors[b]:a.stops[b].color},_lookupData:function(a,b){var d;if(b){var c=0,f=b.length-1;k.some(b,function(b,d){if(a<b)return f=d,!0;c=d;return!1});d=[c,f,(a-b[c])/(b[f]-b[c])]}return d},_meterIn:{inches:39.3701,feet:3.28084,yards:1.09361,miles:6.21371E-4,"nautical-miles":5.39957E-4,millimeters:1E3,centimeters:100,decimeters:10,meters:1,kilometers:0.001,"decimal-degrees":180/20015077},toJson:function(){var a=this.proportionalSymbolInfo,b,d=this.colorInfo,c=this.opacityInfo,f=this.rotationInfo;b=f&&
f.field;var e=f&&(f.expression||b&&(h.isFunction(b)?b:"["+b+"]"));d&&(d=h.mixin({},d),d.colors&&(d.colors=k.map(d.colors,function(a){return h.isArray(a)?h.clone(a):m.toJsonColor(a)})),d.stops&&(d.stops=k.map(d.stops,function(a){a=h.mixin({},a);a.color&&(a.color=h.isArray(a.color)?h.clone(a.color):m.toJsonColor(a.color));return a})));c&&(c=h.mixin({},c),c.opacityValues&&(c.opacityValues=c.opacityValues.slice(0)),c.stops&&(c.stops=k.map(c.stops,function(a){return h.mixin({},a)})));if(a&&(a=h.mixin({},
a),a.minSize&&(a.minSize=p.px2pt(a.minSize)),a.maxSize&&(a.maxSize=p.px2pt(a.maxSize)),b=a.legendOptions))if(a.legendOptions=h.mixin({},b),b=b.customValues)a.legendOptions.customValues=b.slice(0);return{rotationType:e&&(f.type||"geographic"),rotationExpression:e,colorInfo:d,opacityInfo:c,proportionalSymbolInfo:a}}})});
//@ sourceMappingURL=Renderer.js.map