//>>built
define("esri/layers/LabelLayer","require dojo/_base/declare dojo/_base/lang dojo/number dojo/_base/array dojo/_base/connect dojo/has dojox/gfx/_base ../kernel ../lang ../graphic ../PopupInfo ./labelLayerUtils/DynamicLabelClass ./labelLayerUtils/StaticLabelClass ../symbols/TextSymbol ../symbols/ShieldLabelSymbol ../geometry/Extent ../geometry/Point ./GraphicsLayer ./LabelClass ../renderers/SimpleRenderer".split(" "),function(E,t,l,u,v,m,F,r,G,s,w,x,y,z,n,p,A,B,C,q,D){return t(C,{declaredClass:"esri.layers.LabelLayer",
constructor:function(a){this.id="labels";this.featureLayers=[];this._featureLayerInfos=[];this._preparedLabels=[];this._engineType="STATIC";this._mapEventHandlers=[];a&&(a.id&&(this.id=a.id),a.mode&&(this._engineType="DYNAMIC"===a.mode.toUpperCase()?"DYNAMIC":"STATIC"))},_setMap:function(a){var d=this.inherited(arguments);this._map&&this._mapEventHandlers.push(this._map.on("extent-change",l.hitch(this,"refresh")));this.refresh();return d},_unsetMap:function(){var a;for(a=0;a<this._mapEventHandlers.length;a++)m.disconnect(this._mapEventHandlers[a]);
this.refresh();this.inherited(arguments)},setAlgorithmType:function(a){this._engineType=a&&"DYNAMIC"===a.toUpperCase()?"DYNAMIC":"STATIC";this.refresh()},addFeatureLayer:function(a,d,c,b){if(!this.getFeatureLayer(a.layerId)){var h=[];h.push(a.on("update-end",l.hitch(this,"refresh")));h.push(a.on("suspend",l.hitch(this,"refresh")));h.push(a.on("resume",l.hitch(this,"refresh")));h.push(a.on("edits-complete",l.hitch(this,"refresh")));h.push(a.on("labeling-info-change",l.hitch(this,"refresh")));h.push(a.on("time-extent-change",
l.hitch(this,"refresh")));h.push(a.on("show-labels-change",l.hitch(this,"refresh")));this._featureLayerInfos.push({FeatureLayer:a,LabelExpressionInfo:c,LabelingOptions:b,LabelRenderer:d,EventHandlers:h});this.featureLayers.push(a);this.refresh()}},getFeatureLayer:function(a){var d,c;for(d=0;d<this.featureLayers.length;d++)if(c=this.featureLayers[d],void 0!==c&&c.id==a)return c;return null},removeFeatureLayer:function(a){var d;a=this.getFeatureLayer(a);if(void 0!==a&&(d=v.indexOf(this.featureLayers,
a),-1<d)){this.featureLayers.splice(d,1);for(a=0;a<this._featureLayerInfos[d].EventHandlers.length;a++)m.disconnect(this._featureLayerInfos[d].EventHandlers[a]);this._featureLayerInfos.splice(d,1);this.refresh()}},removeAllFeatureLayers:function(){var a;for(a=0;a<this.featureLayers.length;a++){for(var d=0;d<this._featureLayerInfos[a].EventHandlers.length;d++)m.disconnect(this._featureLayerInfos[a].EventHandlers[d]);this.featureLayers=[];this._featureLayerInfos=[]}this.refresh()},getFeatureLayers:function(){return this.featureLayers},
getFeatureLayerInfo:function(a){var d,c;for(d=0;d<this.featureLayers.length;d++)if(c=this.featureLayers[d],void 0!==c&&c.id==a)return this._featureLayerInfos[d];return null},refresh:function(a){var d,c,b,h,g,e=[],f="DYNAMIC"===this._engineType?new y:new z;if(this._map){f.setMap(this._map,this);this._preparedLabels=[];for(a=0;a<this.featureLayers.length;a++)if(c=this.featureLayers[a],c.visible&&c.showLabels&&c.visibleAtMapScale&&!c._suspended)if(d=this._featureLayerInfos[a],d.LabelRenderer){if(e=c.labelingInfo)if(g=
e[0])h=this._getLabelExpression(g),this._convertOptions(g);b=d.LabelRenderer;d.LabelExpressionInfo&&(h=d.LabelExpressionInfo);g=this._convertOptions(null);d.LabelingOptions&&(void 0!==d.LabelingOptions.lineLabelPlacement&&(g.lineLabelPlacement=d.LabelingOptions.lineLabelPlacement),void 0!==d.LabelingOptions.lineLabelPosition&&(g.lineLabelPosition=d.LabelingOptions.lineLabelPosition),void 0!==d.LabelingOptions.labelRotation&&(g.labelRotation=d.LabelingOptions.labelRotation));b instanceof q&&(h=this._getLabelExpression(b),
b=new D(b.symbol),g=this._convertOptions(b));this._addLabels(c,b,h,g)}else if(e=c.labelingInfo)for(d=e.length-1;0<=d;d--)if(g=e[d])b=new q(g instanceof q?g.toJson():g),h=this._getLabelExpression(g),g=this._convertOptions(g),this._addLabels(c,b,h,g);h=f._process(this._preparedLabels);this.clear();this.drawLabels(this._map,h)}},drawLabels:function(a,d){this._scale=(a.extent.xmax-a.extent.xmin)/a.width;var c;for(c=0;c<d.length;c++){var b=d[c],h=b.x,g=b.y,e=b.text,f=b.angle,k=b.layer.labelSymbol;"polyline"==
b.layer.geometry.type&&b.layer.options.labelRotation?k.setAngle(f*(180/Math.PI)):k.setAngle(0);k.setText(e);b=h;k instanceof n&&(h=k.getHeight(),f=Math.sin(f),b-=0.25*h*this._scale*f,g-=0.33*h*this._scale);f=new w(new B(b,g,a.extent.spatialReference));f.setSymbol(k);this.add(f)}},_addLabels:function(a,d,c,b){var h,g,e,f;if(this._isWithinScaleRange(d.minScale,d.maxScale)&&c&&""!==c)for(h=0;h<a.graphics.length;h++)g=a.graphics[h],!1!==g.visible&&(e=g.geometry,this._isWhere(d.where,g.attributes)&&this._isWithinScreenArea(e)&&
(f=this._buildLabelText(c,g.attributes,a.fields,b),this._addLabel(f,d,a.renderer,g,b,e)))},_isWithinScreenArea:function(a){a="point"===a.type?new A(a.x,a.y,a.x,a.y,a.spatialReference):a.getExtent();a=this._intersects(this._map,a);return null===a||0===a.length?!1:!0},_isWithinScaleRange:function(a,d){var c=this._map.getScale();return 0<a&&c>=a||0<d&&c<=d?!1:!0},_isWhere:function(a,d){try{if(!a)return!0;if(a){var c=a.split(" ");if(3===c.length)return this._sqlEquation(d[c[0].substr(1,c[0].length-2)],
c[1],c[2]);if(7===c.length){var b=this._sqlEquation(d[c[0].substr(1,c[0].length-2)],c[1],c[2]),h=c[3],g=this._sqlEquation(d[c[4].substr(1,c[4].length-2)],c[5],c[6]);switch(h){case "AND":return b&&g;case "OR":return b||g}}}return!1}catch(e){}},_sqlEquation:function(a,d,c){switch(d){case "\x3d":return a==c?!0:!1;case "\x3c\x3e":return a!=c?!0:!1;case "\x3e":return a>c?!0:!1;case "\x3e\x3d":return a>=c?!0:!1;case "\x3c":return a<c?!0:!1;case "\x3c\x3d":return a<=c?!0:!1}return!1},_addLabel:function(a,
d,c,b,h,g){var e,f,k,m;if(a&&""!==l.trim(a)&&d){e=d.getSymbol(b);e instanceof n?(e=new n(e.toJson()),e.setVerticalAlignment("baseline"),e.setHorizontalAlignment("center")):e=e instanceof p?new p(e.toJson()):new n;e.setText(a);d.symbol=e;if(f=this._getProportionalSize(d.sizeInfo,b.attributes))e instanceof n?e.setSize(f):e instanceof p&&(e.setWidth(f),e.setHeight(f));k=f=0;if(c)if(m=c.getSize(b),c=c.getSymbol(b),0!==m)k=f=m;else if(c)if("simplemarkersymbol"==c.type)k=f=c.size;else if("picturemarkersymbol"==
c.type)f=c.width,k=c.height;else if("simplelinesymbol"==c.type||"cartographiclinesymbol"==c.type)f=c.width;c={};c.graphic=b;c.options=h;c.geometry=g;c.labelRenderer=d;c.labelSymbol=e;c.labelWidth=e.getWidth()/2;c.labelHeight=e.getHeight()/2;c.symbolWidth=r.normalizedLength(f)/2;c.symbolHeight=r.normalizedLength(k)/2;c.text=a;c.angle=e.angle;this._preparedLabels.push(c)}},_buildLabelText:function(a,d,c,b){return a.replace(/{[^}]*}/g,function(a){var g,e=a;for(g=0;g<c.length;g++)if("{"+c[g].name+"}"==
a){var e=d[c[g].name],f=c[g].domain;if(f&&l.isObject(f)){if("codedValue"==f.type)for(a=0;a<f.codedValues.length;a++)f.codedValues[a].code==e&&(e=f.codedValues[a].name);else"range"==f.type&&f.minValue<=e&&e<=f.maxValue&&(e=f.name);break}f=c[g].type;if("esriFieldTypeDate"==f)(f="DateFormat"+x.prototype._dateFormats[b&&b.dateFormat||"shortDate"])&&(e=s.substitute({myKey:e},"${myKey:"+f+"}"));else if("esriFieldTypeInteger"==f||"esriFieldTypeSmallInteger"==f||"esriFieldTypeLong"==f||"esriFieldTypeDouble"==
f)b&&b.numberFormat&&(b.numberFormat.digitSeparator&&b.numberFormat.places)&&(e=u.format(e,{places:b.numberFormat.places}))}return e})},_getLabelExpression:function(a){return a.labelExpressionInfo?a.labelExpressionInfo.value:this._validSyntax(a.labelExpression)?this._convertLabelExpression(a.labelExpression):""},_validSyntax:function(a){return/^(\s*\[[^\]]+\]\s*)+$/i.test(a)},_convertLabelExpression:function(a){return a.replace(RegExp("\\[","g"),"{").replace(RegExp("\\]","g"),"}")},_getProportionalSize:function(a,
d){if(!a)return null;var c=s.substitute(d,"${"+a.field+"}",{first:!0});return!a.minSize||!a.maxSize||!a.minDataValue||!a.maxDataValue||!c||0>=a.maxDataValue-a.minDataValue?null:(a.maxSize-a.minSize)/(a.maxDataValue-a.minDataValue)*(c-a.minDataValue)+a.minSize},_convertOptions:function(a){var d="shortDate",c=null,b="",h=!0;a&&(d=a.dateFormat,c=a.numberFormat,b=a.labelPlacement);if("always-horizontal"==b||"esriServerPolygonPlacementAlwaysHorizontal"==b)h=!1;return{dateFormat:d,numberFormat:c,pointPriorities:"above-center"==
b||"esriServerPointLabelPlacementAboveCenter"==b?"AboveCenter":"above-left"==b||"esriServerPointLabelPlacementAboveLeft"==b?"AboveLeft":"above-right"==b||"esriServerPointLabelPlacementAboveRight"==b?"AboveRight":"below-center"==b||"esriServerPointLabelPlacementBelowCenter"==b?"BelowCenter":"below-left"==b||"esriServerPointLabelPlacementBelowLeft"==b?"BelowLeft":"below-right"==b||"esriServerPointLabelPlacementBelowRight"==b?"BelowRight":"center-center"==b||"esriServerPointLabelPlacementCenterCenter"==
b?"CenterCenter":"center-left"==b||"esriServerPointLabelPlacementCenterLeft"==b?"CenterLeft":"center-right"==b||"esriServerPointLabelPlacementCenterRight"==b?"CenterRight":"AboveRight",lineLabelPlacement:"above-start"==b||"below-start"==b||"center-start"==b?"PlaceAtStart":"above-end"==b||"below-end"==b||"center-end"==b?"PlaceAtEnd":"PlaceAtCenter",lineLabelPosition:"above-after"==b||"esriServerLinePlacementAboveAfter"==b||"above-along"==b||"esriServerLinePlacementAboveAlong"==b||"above-before"==b||
"esriServerLinePlacementAboveBefore"==b||"above-start"==b||"esriServerLinePlacementAboveStart"==b||"above-end"==b||"esriServerLinePlacementAboveEnd"==b?"Above":"below-after"==b||"esriServerLinePlacementBelowAfter"==b||"below-along"==b||"esriServerLinePlacementBelowAlong"==b||"below-before"==b||"esriServerLinePlacementBelowBefore"==b||"below-start"==b||"esriServerLinePlacementBelowStart"==b||"below-end"==b||"esriServerLinePlacementBelowEnd"==b?"Below":"center-after"==b||"esriServerLinePlacementCenterAfter"==
b||"center-along"==b||"esriServerLinePlacementCenterAlong"==b||"center-before"==b||"esriServerLinePlacementCenterBefore"==b||"center-start"==b||"esriServerLinePlacementCenterStart"==b||"center-end"==b||"esriServerLinePlacementCenterEnd"==b?"OnLine":"Above",labelRotation:h,howManyLabels:"OneLabel"}}})});
//@ sourceMappingURL=LabelLayer.js.map