//>>built
define("esri/IdentityManagerBase","dojo/_base/declare dojo/_base/config dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/_base/json dojo/_base/url dojo/sniff dojo/cookie dojo/io-query dojo/regexp ./kernel ./config ./lang ./ServerInfo ./urlUtils ./deferredUtils ./request ./Evented ./OAuthCredential ./arcgis/OAuthInfo".split(" "),function(G,x,q,f,H,A,y,I,J,Q,R,r,B,w,C,s,K,D,L,M,S){var z={},E=function(a){var b=(new y(a.owningSystemUrl)).host;a=(new y(a.server)).host;var d=/.+\.arcgis\.com$/i;
return d.test(b)&&d.test(a)},F=function(a,b){return!(!E(a)||!b||!f.some(b,function(b){return b.test(a.server)}))},v,P=G(L,{declaredClass:"esri.IdentityManagerBase",constructor:function(){this._portalConfig=q.getObject("esriGeowConfig");this.serverInfos=[];this.oAuthInfos=[];this.credentials=[];this._soReqs=[];this._xoReqs=[];this._portals=[];this._getOAuthHash()},defaultTokenValidity:60,tokenValidity:null,signInPage:null,useSignInPage:!0,normalizeWebTierAuth:!1,_busy:null,_oAuthHash:null,_gwTokenUrl:"/sharing/generateToken",
_agsRest:"/rest/services",_agsPortal:/\/sharing(\/|$)/i,_agsAdmin:/https?:\/\/[^\/]+\/[^\/]+\/admin\/?(\/.*)?$/i,_adminSvcs:/\/admin\/services(\/|$)/i,_agolSuffix:".arcgis.com",_gwDomains:[{regex:/https?:\/\/www\.arcgis\.com/i,tokenServiceUrl:"https://www.arcgis.com/sharing/generateToken"},{regex:/https?:\/\/dev\.arcgis\.com/i,tokenServiceUrl:"https://dev.arcgis.com/sharing/generateToken"},{regex:/https?:\/\/.*dev[^.]*\.arcgis\.com/i,tokenServiceUrl:"https://devext.arcgis.com/sharing/generateToken"},
{regex:/https?:\/\/.*qa[^.]*\.arcgis\.com/i,tokenServiceUrl:"https://qaext.arcgis.com/sharing/generateToken"},{regex:/https?:\/\/.*.arcgis\.com/i,tokenServiceUrl:"https://www.arcgis.com/sharing/generateToken"}],_legacyFed:[],_regexSDirUrl:/http.+\/rest\/services\/?/ig,_regexServerType:/(\/(MapServer|GeocodeServer|GPServer|GeometryServer|ImageServer|NAServer|FeatureServer|GeoDataServer|GlobeServer|MobileServer|GeoenrichmentServer)).*/ig,_gwUser:/http.+\/users\/([^\/]+)\/?.*/i,_gwItem:/http.+\/items\/([^\/]+)\/?.*/i,
_gwGroup:/http.+\/groups\/([^\/]+)\/?.*/i,_errorCodes:[499,498,403,401],_rePortalTokenSvc:/\/sharing(\/rest)?\/generatetoken/i,_publicUrls:[/\/arcgis\/tokens/i,/\/sharing(\/rest)?\/generatetoken/i,/\/rest\/info/i],registerServers:function(a){var b=this.serverInfos;b?(a=f.filter(a,function(a){return!this.findServerInfo(a.server)},this),this.serverInfos=b.concat(a)):this.serverInfos=a;f.forEach(a,function(a){a.owningSystemUrl&&this._portals.push(a.owningSystemUrl);if(a.hasPortal){this._portals.push(a.server);
var b=B.defaults.io.corsEnabledServers,e=this._getOrigin(a.tokenServiceUrl);s.canUseXhr(a.server)||b.push(a.server.replace(/^https?:\/\//i,""));s.canUseXhr(e)||b.push(e.replace(/^https?:\/\//i,""))}},this)},registerOAuthInfos:function(a){var b=this.oAuthInfos;b?(a=f.filter(a,function(a){return!this.findOAuthInfo(a.portalUrl)},this),this.oAuthInfos=b.concat(a)):this.oAuthInfos=a},registerToken:function(a){var b=this._sanitizeUrl(a.server),d=this.findServerInfo(b),c;d||(d=new C,d.server=this._getOrigin(b),
d.tokenServiceUrl=this._getTokenSvcUrl(b),d.hasPortal=!0,this.registerServers([d]));(c=this.findCredential(b,a.userId))?q.mixin(c,a):(c=new v({userId:a.userId,server:d.server,token:a.token,expires:a.expires,ssl:a.ssl,scope:this._isServerRsrc(b)?"server":"portal"}),c.resources=[b],this.credentials.push(c));c.onTokenChange(!1)},toJson:function(){return w.fixJson({serverInfos:f.map(this.serverInfos,function(a){return a.toJson()}),oAuthInfos:f.map(this.oAuthInfos,function(a){return a.toJson()}),credentials:f.map(this.credentials,
function(a){return a.toJson()})})},initialize:function(a){if(a){q.isString(a)&&(a=A.fromJson(a));var b=a.serverInfos,d=a.oAuthInfos;a=a.credentials;if(b){var c=[];f.forEach(b,function(a){a.server&&a.tokenServiceUrl&&c.push(a.declaredClass?a:new C(a))});c.length&&this.registerServers(c)}if(d){var e=[];f.forEach(d,function(a){a.appId&&e.push(a.declaredClass?a:new S(a))});e.length&&this.registerOAuthInfos(e)}a&&f.forEach(a,function(a){a.userId&&a.server&&(a.token&&a.expires&&a.expires>(new Date).getTime())&&
(a=a.declaredClass?a:new v(a),a.onTokenChange(),this.credentials.push(a))},this)}},findServerInfo:function(a){var b;a=this._sanitizeUrl(a);f.some(this.serverInfos,function(d){s.hasSameOrigin(d.server,a,!0)&&(b=d);return!!b});return b},findOAuthInfo:function(a){var b;a=this._sanitizeUrl(a);f.some(this.oAuthInfos,function(d){s.hasSameOrigin(d.portalUrl,a,!0)&&(b=d);return!!b});return b},findCredential:function(a,b){var d,c;a=this._sanitizeUrl(a);c=this._isServerRsrc(a)?"server":"portal";b?f.some(this.credentials,
function(e){s.hasSameOrigin(a,e.server,!0)&&b===e.userId&&e.scope===c&&(d=e);return!!d},this):f.some(this.credentials,function(b){s.hasSameOrigin(a,b.server,!0)&&-1!==this._getIdenticalSvcIdx(a,b)&&b.scope===c&&(d=b);return!!d},this);return d},getCredential:function(a,b){var d,c,e=!0;w.isDefined(b)&&(q.isObject(b)?(d=!!b.token,c=b.error,e=!1!==b.prompt):d=b);a=this._sanitizeUrl(a);var g=new H(K._dfdCanceller),f=this._isAdminResource(a),n=d&&this._doPortalSignIn(a)?this._getEsriAuthCookie():null;d=
d?this.findCredential(a):null;if(n||d)return e=Error("You are currently signed in as: '"+(n&&n.email||d&&d.userId)+"'. You do not have access to this resource: "+a),e.code="IdentityManagerBase.1",e.httpCode=c&&c.httpCode,e.messageCode=c?c.messageCode:null,e.subcode=c?c.subcode:null,e.details=c?c.details:null,e.log=x.isDebug,g.errback(e),g;if(c=this._findCredential(a,b))return g.callback(c),g;if(c=this.findServerInfo(a))!c.hasServer&&this._isServerRsrc(a)&&(c._restInfoDfd=this._getTokenSvcUrl(a,!0),
c.hasServer=!0);else{n=this._getTokenSvcUrl(a);if(!n)return e=Error("Unknown resource - could not find token service endpoint."),e.code="IdentityManagerBase.2",e.log=x.isDebug,g.errback(e),g;c=new C;c.server=this._getOrigin(a);q.isString(n)?(c.tokenServiceUrl=n,e&&!this._findOAuthInfo(a)&&(c._selfDfd=this._getPortalSelf(n.replace(this._rePortalTokenSvc,"/sharing/rest/portals/self"),a)),c.hasPortal=!0):(c._restInfoDfd=n,c.hasServer=!0);this.registerServers([c])}return this._enqueue(a,c,b,g,f)},getResourceName:function(a){return this._isRESTService(a)?
a.replace(this._regexSDirUrl,"").replace(this._regexServerType,"")||"":this._gwUser.test(a)&&a.replace(this._gwUser,"$1")||this._gwItem.test(a)&&a.replace(this._gwItem,"$1")||this._gwGroup.test(a)&&a.replace(this._gwGroup,"$1")||""},generateToken:function(a,b,d){var c,e,f,m,n,N,t=new y(window.location.href.toLowerCase()),u=this._getEsriAuthCookie(),l,O=a.webTierAuth&&!b;m=a.shortLivedTokenValidity;var p;b&&(p=r.id.tokenValidity||m||r.id.defaultTokenValidity,p>m&&(p=m));d&&(c=d.isAdmin,e=d.serverUrl,
f=d.token,N=d.ssl,a.customParameters=d.customParameters);if(c)m=a.adminTokenServiceUrl;else if(m=a.tokenServiceUrl,n=new y(m.toLowerCase()),u&&(l=(l=u.auth_tier)&&l.toLowerCase()),("web"===l||a.webTierAuth)&&d&&d.serverUrl&&!N&&"http"===t.scheme&&(s.hasSameOrigin(t.uri,m,!0)||"https"===n.scheme&&t.host===n.host&&"7080"===t.port&&"7443"===n.port))m=m.replace(/^https:/i,"http:").replace(/:7443/i,":7080");d=D(q.mixin({url:m,content:q.mixin({request:"getToken",username:b&&b.username,password:b&&b.password,
serverUrl:e,token:f,expiration:p,referer:c||this._rePortalTokenSvc.test(a.tokenServiceUrl)?window.location.host:null,client:c?"referer":null,f:"json"},a.customParameters),handleAs:"json",callbackParamName:O?"callback":void 0},d&&d.ioArgs),{usePost:!O,disableIdentityLookup:!0,useProxy:this._useProxy(a,d)});d.addCallback(function(c){if(!c||!c.token)return c=Error("Unable to generate token"),c.code="IdentityManagerBase.3",c.log=x.isDebug,c;var d=a.server;z[d]||(z[d]={});b&&(z[d][b.username]=b.password);
c.validity=p;return c});d.addErrback(function(a){});return d},isBusy:function(){return!!this._busy},checkSignInStatus:function(a){return this.getCredential(a,{prompt:!1})},setRedirectionHandler:function(a){this._redirectFunc=a},setProtocolErrorHandler:function(a){this._protocolFunc=a},signIn:function(){},oAuthSignIn:function(){},onCredentialCreate:function(){},onCredentialsDestroy:function(){},destroyCredentials:function(){if(this.credentials){var a=this.credentials.slice();f.forEach(a,function(a){a.destroy()})}this.onCredentialsDestroy()},
_getOAuthHash:function(){var a=window.location.hash;if(a){"#"===a.charAt(0)&&(a=a.substring(1));var a=Q.queryToObject(a),b=!1;a.access_token&&a.expires_in&&a.state&&a.hasOwnProperty("username")?(a.state=A.fromJson(a.state),this._oAuthHash=a,b=!0):a.error&&a.error_description&&"access_denied"===a.error&&(b=!0);if(b&&(!I("ie")||8<I("ie")))window.location.hash=""}},_findCredential:function(a,b){var d=-1,c,e,g,m,n=b&&b.token;c=b&&b.resource;var r=this._isServerRsrc(a)?"server":"portal",t=f.filter(this.credentials,
function(b){return s.hasSameOrigin(b.server,a,!0)&&b.scope===r});a=c||a;if(t.length)if(1===t.length)if(c=t[0],g=(e=(m=this.findServerInfo(c.server))&&m.owningSystemUrl)&&this.findCredential(e,c.userId),d=this._getIdenticalSvcIdx(a,c),n)-1!==d&&(c.resources.splice(d,1),this._removeResource(a,g));else return-1===d&&c.resources.push(a),this._addResource(a,g),c;else{var u,l;f.some(t,function(b){l=this._getIdenticalSvcIdx(a,b);return-1!==l?(u=b,g=(e=(m=this.findServerInfo(u.server))&&m.owningSystemUrl)&&
this.findCredential(e,u.userId),d=l,!0):!1},this);if(n)u&&(u.resources.splice(d,1),this._removeResource(a,g));else if(u)return this._addResource(a,g),u}},_findOAuthInfo:function(a){var b=this.findOAuthInfo(a);b||f.some(this.oAuthInfos,function(d){this._isIdProvider(d.portalUrl,a)&&(b=d);return!!b},this);return b},_addResource:function(a,b){b&&-1===this._getIdenticalSvcIdx(a,b)&&b.resources.push(a)},_removeResource:function(a,b){var d=-1;b&&(d=this._getIdenticalSvcIdx(a,b),-1<d&&b.resources.splice(d,
1))},_useProxy:function(a,b){return b&&b.isAdmin&&!s.hasSameOrigin(a.adminTokenServiceUrl,window.location.href)||!this._isPortalDomain(a.tokenServiceUrl)&&10.1==a.currentVersion&&!s.hasSameOrigin(a.tokenServiceUrl,window.location.href)},_getOrigin:function(a){a=new y(a);return a.scheme+"://"+a.host+(w.isDefined(a.port)?":"+a.port:"")},_sanitizeUrl:function(a){a=s.fixUrl(q.trim(a));var b=(B.defaults.io.proxyUrl||"").toLowerCase(),d=b?a.toLowerCase().indexOf(b+"?"):-1;-1!==d&&(a=a.substring(d+b.length+
1));return s.urlToObject(a).path},_isRESTService:function(a){return-1<a.indexOf(this._agsRest)},_isAdminResource:function(a){return this._agsAdmin.test(a)||this._adminSvcs.test(a)},_isServerRsrc:function(a){return this._isRESTService(a)||this._isAdminResource(a)},_isIdenticalService:function(a,b){var d;if(this._isRESTService(a)&&this._isRESTService(b)){var c=this._getSuffix(a).toLowerCase(),e=this._getSuffix(b).toLowerCase();(d=c===e)||(d=/(.*)\/(MapServer|FeatureServer).*/ig,d=c.replace(d,"$1")===
e.replace(d,"$1"))}else this._isAdminResource(a)&&this._isAdminResource(b)?d=!0:!this._isServerRsrc(a)&&!this._isServerRsrc(b)&&this._isPortalDomain(a)&&(d=!0);return d},_isPortalDomain:function(a){a=a.toLowerCase();var b=(new y(a)).authority,d=this._portalConfig,c=-1!==b.indexOf(this._agolSuffix);!c&&d&&(c=s.hasSameOrigin(d.restBaseUrl,a,!0));if(!c){if(!this._arcgisUrl&&(d=q.getObject("esri.arcgis.utils.arcgisUrl")))this._arcgisUrl=(new y(d)).authority;this._arcgisUrl&&(c=this._arcgisUrl.toLowerCase()===
b)}c||(c=f.some(this._portals,function(b){return s.hasSameOrigin(b,a,!0)}));return c=c||this._agsPortal.test(a)},_isIdProvider:function(a,b){var d=-1,c=-1;f.forEach(this._gwDomains,function(e,f){-1===d&&e.regex.test(a)&&(d=f);-1===c&&e.regex.test(b)&&(c=f)});var e=!1;if(-1<d&&-1<c)if(0===d||4===d){if(0===c||4===c)e=!0}else if(1===d){if(1===c||2===c)e=!0}else 2===d?2===c&&(e=!0):3===d&&3===c&&(e=!0);if(!e){var g=this.findServerInfo(b),m=g&&g.owningSystemUrl;m&&E(g)&&(this._isPortalDomain(m)&&this._isIdProvider(a,
m))&&(e=!0)}return e},_isPublic:function(a){a=this._sanitizeUrl(a);return f.some(this._publicUrls,function(b){return b.test(a)})},_getIdenticalSvcIdx:function(a,b){var d=-1;f.some(b.resources,function(b,e){return this._isIdenticalService(a,b)?(d=e,!0):!1},this);return d},_getSuffix:function(a){return a.replace(this._regexSDirUrl,"").replace(this._regexServerType,"$1")},_getTokenSvcUrl:function(a){var b,d;if((b=this._isRESTService(a))||this._isAdminResource(a))return d=a.toLowerCase().indexOf(b?this._agsRest:
"/admin/"),b=a.substring(0,d)+"/admin/generateToken",a=a.substring(0,d)+"/rest/info",d=D({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}),d.adminUrl_=b,d;if(this._isPortalDomain(a)){var c="";f.some(this._gwDomains,function(b){b.regex.test(a)&&(c=b.tokenServiceUrl);return!!c});c||f.some(this._portals,function(b){s.hasSameOrigin(b,a,!0)&&(c=b+this._gwTokenUrl);return!!c},this);c||(d=a.toLowerCase().indexOf("/sharing"),-1!==d&&(c=a.substring(0,d)+this._gwTokenUrl));c||(c=this._getOrigin(a)+
this._gwTokenUrl);c&&(b=(new y(a)).port,/^http:\/\//i.test(a)&&"7080"===b&&(c=c.replace(/:7080/i,":7443")),c=c.replace(/http:/i,"https:"));return c}if(-1!==a.toLowerCase().indexOf("premium.arcgisonline.com"))return"https://premium.arcgisonline.com/server/tokens"},_getPortalSelf:function(a,b){"https:"===window.location.protocol?a=a.replace(/^http:/i,"https:").replace(/:7080/i,":7443"):/^http:/i.test(b)&&(a=a.replace(/^https:/i,"http:").replace(/:7443/i,":7080"));return D({url:a,content:{f:"json"},
handleAs:"json",callbackParamName:"callback"},{crossOrigin:!1,disableIdentityLookup:!0})},_hasPortalSession:function(){return!!this._getEsriAuthCookie()},_getEsriAuthCookie:function(){var a;if(J.isSupported()){var b=this._getAllCookies("esri_auth"),d;for(d=0;d<b.length;d++){var c=A.fromJson(b[d]);if(c.portalApp){a=c;break}}}return a},_getAllCookies:function(a){var b=[],d=document.cookie.match(RegExp("(?:^|; )"+R.escapeString(a)+"\x3d([^;]*)","g"));if(d)for(a=0;a<d.length;a++){var c=d[a],e=c.indexOf("\x3d");
-1<e&&(c=c.substring(e+1),b.push(decodeURIComponent(c)))}return b},_doPortalSignIn:function(a){if(J.isSupported()){var b=this._getEsriAuthCookie(),d=this._portalConfig,c=window.location.href,e=this.findServerInfo(a);if(this.useSignInPage&&(d||this._isPortalDomain(c)||b)&&(e?e.hasPortal||e.owningSystemUrl&&this._isPortalDomain(e.owningSystemUrl):this._isPortalDomain(a))&&(this._isIdProvider(c,a)||d&&(s.hasSameOrigin(d.restBaseUrl,a,!0)||this._isIdProvider(d.restBaseUrl,a))||s.hasSameOrigin(c,a,!0)))return!0}return!1},
_checkProtocol:function(a,b,d,c){var e=!0;c=c?b.adminTokenServiceUrl:b.tokenServiceUrl;if(0===q.trim(c).toLowerCase().indexOf("https:")&&0!==window.location.href.toLowerCase().indexOf("https:")&&(!B.defaults.io.useCors||!s.canUseXhr(c)&&!s.canUseXhr(s.getProxyUrl(!0).path)))(e=this._protocolFunc?!!this._protocolFunc({resourceUrl:a,serverInfo:b}):!1)||(a=Error("Aborted the Sign-In process to avoid sending password over insecure connection."),a.code="IdentityManagerBase.4",a.log=x.isDebug,d(a));return e},
_enqueue:function(a,b,d,c,e,f){c||(c=new H(K._dfdCanceller));c.resUrl_=a;c.sinfo_=b;c.options_=d;c.admin_=e;c.refresh_=f;this._busy?s.hasSameOrigin(a,this._busy.resUrl_,!0)?this._soReqs.push(c):this._xoReqs.push(c):this._doSignIn(c);return c},_doSignIn:function(a){this._busy=a;var b=this,d=function(c){var d=a.options_&&a.options_.resource,e=a.resUrl_,p=a.refresh_,k=!1;-1===f.indexOf(b.credentials,c)&&(p&&-1!==f.indexOf(b.credentials,p)?(p.userId=c.userId,p.token=c.token,p.expires=c.expires,p.validity=
c.validity,p.ssl=c.ssl,p.creationTime=c.creationTime,k=!0,c=p):b.credentials.push(c));c.resources||(c.resources=[]);c.resources.push(d||e);c.scope=b._isServerRsrc(e)?"server":"portal";c.onTokenChange();var d=b._soReqs,h={};b._soReqs=[];f.forEach(d,function(a){if(!this._isIdenticalService(e,a.resUrl_)){var b=this._getSuffix(a.resUrl_);h[b]||(h[b]=!0,c.resources.push(a.resUrl_))}},b);a.callback(c);f.forEach(d,function(a){a.callback(c)});b._busy=a.resUrl_=a.sinfo_=a.refresh_=null;if(!k)b.onCredentialCreate({credential:c});
b._soReqs.length&&b._doSignIn(b._soReqs.shift());b._xoReqs.length&&b._doSignIn(b._xoReqs.shift())},c=function(c){a.errback(c);b._busy=a.resUrl_=a.sinfo_=a.refresh_=null;b._soReqs.length&&b._doSignIn(b._soReqs.shift());b._xoReqs.length&&b._doSignIn(b._xoReqs.shift())},e=function(e,l,f,p){var k=a.sinfo_,h=!a.options_||!1!==a.options_.prompt;b._doPortalSignIn(a.resUrl_)?(l=b._getEsriAuthCookie(),e=b._portalConfig,l?d(new v({userId:l.email,server:k.server,token:l.token,expires:null})):h?(l=window.location.href,
h=b.signInPage?b.signInPage:e?e.baseUrl+e.signin:b._isIdProvider(l,a.resUrl_)?b._getOrigin(l)+"/home/signin.html":k.tokenServiceUrl.replace(b._rePortalTokenSvc,"")+"/home/signin.html",h=h.replace(/http:/i,"https:"),e&&!1===e.useSSL&&(h=h.replace(/https:/i,"http:")),0===l.toLowerCase().replace("https","http").indexOf(h.toLowerCase().replace("https","http"))?(k=Error("Cannot redirect to Sign-In page from within Sign-In page. URL of the resource that triggered this workflow: "+a.resUrl_),k.code="IdentityManagerBase.5",
k.log=x.isDebug,c(k)):b._redirectFunc?b._redirectFunc({signInPage:h,returnUrlParamName:"returnUrl",returnUrl:l,resourceUrl:a.resUrl_,serverInfo:k}):window.location=h+"?returnUrl\x3d"+window.escape(l)):(k=Error("User is not signed in."),k.code="IdentityManagerBase.6",k.log=x.isDebug,c(k))):e?d(new v({userId:e,server:k.server,token:f,expires:w.isDefined(p)?Number(p):null,ssl:!!l})):t?(e=t._oAuthCred,e||(l=new M(t,window.localStorage),f=new M(t,window.sessionStorage),l.isValid()&&f.isValid()?l.expires>
f.expires?(e=l,f.destroy()):(e=f,l.destroy()):e=l.isValid()?l:f,t._oAuthCred=e),e.isValid()?d(new v({userId:e.userId,server:k.server,token:e.token,expires:e.expires,ssl:e.ssl,_oAuthCred:e})):b._oAuthHash&&b._oAuthHash.state.portalUrl===t.portalUrl?(h=b._oAuthHash,k=new v({userId:h.username,server:k.server,token:h.access_token,expires:(new Date).getTime()+1E3*Number(h.expires_in),ssl:"true"===h.ssl,oAuthState:h.state,_oAuthCred:e}),e.storage=h.persist?window.localStorage:window.sessionStorage,e.token=
k.token,e.expires=k.expires,e.userId=k.userId,e.ssl=k.ssl,e.save(),b._oAuthHash=null,d(k)):h?a._pendingDfd=b.oAuthSignIn(a.resUrl_,k,t,a.options_).addCallbacks(d,c):(k=Error("User is not signed in."),k.code="IdentityManagerBase.6",k.log=x.isDebug,c(k))):h?b._checkProtocol(a.resUrl_,k,c,a.admin_)&&(h=a.options_,a.admin_&&(h=h||{},h.isAdmin=!0),a._pendingDfd=b.signIn(a.resUrl_,k,h).addCallbacks(d,c)):(k=Error("User is not signed in."),k.code="IdentityManagerBase.6",k.log=x.isDebug,c(k))},g=function(){var e=
a.sinfo_,l=e.owningSystemUrl,g=a.options_,p,k,h;g&&(p=g.token,k=g.error);h=b._findCredential(l,{token:p,resource:a.resUrl_});!h&&E(e)&&f.some(b.credentials,function(a){this._isIdProvider(l,a.server)&&(h=a);return!!h},b);h?(g=b.findCredential(a.resUrl_,h.userId))?d(g):F(e,b._legacyFed)?(g=h.toJson(),g.server=e.server,g.resources=null,d(new v(g))):(a._pendingDfd=b.generateToken(b.findServerInfo(h.server),null,{serverUrl:a.resUrl_,token:h.token,ssl:h.ssl})).addCallbacks(function(b){d(new v({userId:h.userId,
server:e.server,token:b.token,expires:w.isDefined(b.expires)?Number(b.expires):null,ssl:!!b.ssl,isAdmin:a.admin_,validity:b.validity}))},c):(b._busy=null,p&&(a.options_.token=null),(a._pendingDfd=b.getCredential(l.replace(/\/?$/,"/sharing"),{resource:a.resUrl_,token:p,error:k})).addCallbacks(function(c){b._enqueue(a.resUrl_,a.sinfo_,a.options_,a,a.admin_)},function(a){c(a)}))},m=a.sinfo_.owningSystemUrl,n=this._isServerRsrc(a.resUrl_),r=a.sinfo_._restInfoDfd,t=this._findOAuthInfo(a.resUrl_);r?r.addCallbacks(function(c){var d=
a.sinfo_;d.adminTokenServiceUrl=d._restInfoDfd.adminUrl_;d._restInfoDfd=null;d.tokenServiceUrl=q.getObject("authInfo.tokenServicesUrl",!1,c)||q.getObject("authInfo.tokenServiceUrl",!1,c)||q.getObject("tokenServiceUrl",!1,c);d.shortLivedTokenValidity=q.getObject("authInfo.shortLivedTokenValidity",!1,c);d.currentVersion=c.currentVersion;d.owningTenant=c.owningTenant;if(c=d.owningSystemUrl=c.owningSystemUrl)b._portals.push(c),!d.hasPortal&&s.hasSameOrigin(c,a.resUrl_,!0)&&(t||(d._selfDfd=b._getPortalSelf(c.replace(/\/?$/,
"/sharing/rest/portals/self"),a.resUrl_)),d.hasPortal=!0);n&&c?g():e()},function(){a.sinfo_._restInfoDfd=null;var b=Error("Unknown resource - could not find token service endpoint.");b.code="IdentityManagerBase.2";b.log=x.isDebug;c(b)}):n&&m?g():a.sinfo_._selfDfd?(m=function(c){a.sinfo_._selfDfd=null;var d=c&&c.user&&c.user.username,f=c&&c.allSSL;a.sinfo_.webTierAuth=!!d;d&&b.normalizeWebTierAuth?(a.sinfo_._tokenDfd=b.generateToken(a.sinfo_,null,{ssl:f}),c=function(b){a.sinfo_._tokenDfd=null;e(d,
f,b&&b.token,b&&b.expires)},a.sinfo_._tokenDfd.then(c,c)):e(d,f)},a.sinfo_._selfDfd.then(m,m)):e()}});v=G(L,{declaredClass:"esri.Credential",tokenRefreshBuffer:2,constructor:function(a){q.mixin(this,a);this.resources=this.resources||[];w.isDefined(this.creationTime)||(this.creationTime=(new Date).getTime())},_oAuthCred:null,refreshToken:function(){function a(){"portal"===b.scope&&f.forEach(r.id.credentials,function(a){var c=r.id.findServerInfo(a.server),d=c&&c.owningSystemUrl;if(a!==b&&a.userId===
b.userId&&d&&"server"===a.scope&&(s.hasSameOrigin(b.server,d,!0)||r.id._isIdProvider(d,b.server)))F(c,r.id._legacyFed)?(a.token=b.token,a.expires=b.expires,a.creationTime=b.creationTime,a.validity=b.validity,a.onTokenChange()):a.refreshToken()})}var b=this,d=this.resources&&this.resources[0],c=r.id.findServerInfo(this.server),e=c&&c.owningSystemUrl,g=!!e&&"server"===this.scope,m=g&&F(c,r.id._legacyFed),n=g&&r.id.findServerInfo(e),q,t=(q=c.webTierAuth)&&r.id.normalizeWebTierAuth,u=z[this.server],u=
u&&u[this.userId],l={username:this.userId,password:u},v;if(!q||t)if(g&&!n&&f.some(r.id.serverInfos,function(a){r.id._isIdProvider(e,a.server)&&(n=a);return!!n}),q=n&&r.id.findCredential(n.server,this.userId),!g||q)if(m)q.refreshToken();else{if(g)v={serverUrl:d,token:q&&q.token,ssl:q&&q.ssl};else if(t)l=null,v={ssl:this.ssl};else if(u)this.isAdmin&&(v={isAdmin:!0});else{var p;d&&(d=r.id._sanitizeUrl(d),this._enqueued=1,p=r.id._enqueue(d,c,null,null,this.isAdmin,this),p.addCallback(function(){b._enqueued=
0;a()}).addErrback(function(){b._enqueued=0}));return p}return r.id.generateToken(g?n:c,g?null:l,v).addCallback(function(c){b.token=c.token;b.expires=w.isDefined(c.expires)?Number(c.expires):null;b.creationTime=(new Date).getTime();b.validity=c.validity;b.onTokenChange();a()}).addErrback(function(){})}},onTokenChange:function(a){clearTimeout(this._refreshTimer);var b=this.server&&r.id.findServerInfo(this.server),d=(b=b&&b.owningSystemUrl)&&r.id.findServerInfo(b);!1!==a&&(!b||"portal"===this.scope||
d&&d.webTierAuth&&!r.id.normalizeWebTierAuth)&&(w.isDefined(this.expires)||w.isDefined(this.validity))&&this._startRefreshTimer()},onDestroy:function(){},destroy:function(){this.userId=this.server=this.token=this.expires=this.validity=this.resources=this.creationTime=null;this._oAuthCred&&(this._oAuthCred.destroy(),this._oAuthCred=null);var a=f.indexOf(r.id.credentials,this);-1<a&&r.id.credentials.splice(a,1);this.onTokenChange();this.onDestroy()},toJson:function(){return this._toJson()},_toJson:function(){var a=
w.fixJson({userId:this.userId,server:this.server,token:this.token,expires:this.expires,validity:this.validity,ssl:this.ssl,isAdmin:this.isAdmin,creationTime:this.creationTime,scope:this.scope}),b=this.resources;b&&0<b.length&&(a.resources=b);return a},_startRefreshTimer:function(){clearTimeout(this._refreshTimer);var a=6E4*this.tokenRefreshBuffer,b=(this.validity?this.creationTime+6E4*this.validity:this.expires)-(new Date).getTime();0>b&&(b=0);this._refreshTimer=setTimeout(q.hitch(this,this.refreshToken),
b>a?b-a:b)}});P.Credential=v;return P});
//@ sourceMappingURL=IdentityManagerBase.js.map